/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/
import Amenability.HopfModuleCoalgebra
import Amenability.FiniteSubcoalgebra
import Amenability.CompleteSubcoalgebraFlag
import Mathlib.LinearAlgebra.TensorProduct.Finiteness

/-!
# Subspaces generated by a Hopf-module action
-/

open Coalgebra Module TensorProduct

namespace HopfAmenability

noncomputable section

universe u v w

variable {k : Type u} {H : Type v} {M : Type w}
variable [Field k] [Ring H] [HopfAlgebra k H]
variable [AddCommGroup M] [Module k M]
variable [Module H M] [IsScalarTower k H M]

/-- The Hopf action restricted to two subspaces. -/
def restrictedHopfModuleAction (F : Submodule k H) (E : Submodule k M) :
    F ⊗[k] E →ₗ[k] M :=
  hopfModuleAction.comp (TensorProduct.mapIncl F E)

@[simp]
theorem restrictedHopfModuleAction_tmul
    (F : Submodule k H) (E : Submodule k M) (h : F) (m : E) :
    restrictedHopfModuleAction F E (h ⊗ₜ[k] m) = (h : H) • (m : M) :=
  rfl

/-- The span of the action of `F` on `E`. -/
def actionSubspace (F : Submodule k H) (E : Submodule k M) :
    Submodule k M :=
  LinearMap.range (restrictedHopfModuleAction F E)

theorem actionSubspace_eq_map₂ (F : Submodule k H) (E : Submodule k M) :
    actionSubspace F E =
      Submodule.map₂ (Algebra.lsmul k k M).toLinearMap F E := by
  rw [actionSubspace, TensorProduct.map₂_eq_range_lift_comp_mapIncl]
  rfl

theorem actionSubspace_mono_left {F F' : Submodule k H}
    (h : F ≤ F') (E : Submodule k M) :
    actionSubspace F E ≤ actionSubspace F' E := by
  rw [actionSubspace_eq_map₂, actionSubspace_eq_map₂]
  exact Submodule.map₂_le_map₂_left h

theorem actionSubspace_mono_right (F : Submodule k H)
    {E E' : Submodule k M} (h : E ≤ E') :
    actionSubspace F E ≤ actionSubspace F E' := by
  rw [actionSubspace_eq_map₂, actionSubspace_eq_map₂]
  exact Submodule.map₂_le_map₂_right h

theorem product_mem_actionSubspace
    {F : Submodule k H} {E : Submodule k M}
    {h : H} (hh : h ∈ F) {m : M} (hm : m ∈ E) :
    h • m ∈ actionSubspace F E := by
  exact ⟨(⟨h, hh⟩ : F) ⊗ₜ[k] (⟨m, hm⟩ : E), rfl⟩

theorem finiteDimensional_actionSubspace
    (F : Submodule k H) (E : Submodule k M)
    [FiniteDimensional k F] [FiniteDimensional k E] :
    FiniteDimensional k (actionSubspace F E) := by
  rw [actionSubspace]
  infer_instance

noncomputable instance instFiniteDimensionalActionSubspace
    (F : Submodule k H) (E : Submodule k M)
    [FiniteDimensional k F] [FiniteDimensional k E] :
    FiniteDimensional k (actionSubspace F E) :=
  finiteDimensional_actionSubspace F E

section Coalgebra

variable [Coalgebra k M] [IsHopfModuleCoalgebra k H M]

/-- Acting by a subcoalgebra on a subcoalgebra produces a subcoalgebra. -/
theorem IsSubcoalgebra.actionSubspace
    {F : Submodule k H} (hF : IsSubcoalgebra (k := k) F)
    {C : Submodule k M} (hC : IsSubcoalgebra (k := k) C) :
    IsSubcoalgebra (k := k) (actionSubspace F C) := by
  let hFcoal := subcoalgebraCoalgebra F hF
  let hCcoal := subcoalgebraCoalgebra C hC
  let incl : F ⊗[k] C →ₗc[k] H ⊗[k] M :=
    CoalgHom.tensorMapStruct
      (subcoalgebraInclusion F hF) (subcoalgebraInclusion C hC)
  let act : F ⊗[k] C →ₗc[k] M :=
    hopfModuleActionCoalgHom.comp incl
  have htop : IsSubcoalgebra (k := k) (⊤ : Submodule k (F ⊗[k] C)) := by
    intro x hx
    let i : F ⊗[k] C →ₗ[k] (⊤ : Submodule k (F ⊗[k] C)) :=
      LinearMap.codRestrict ⊤ LinearMap.id (fun _ => trivial)
    refine ⟨TensorProduct.map i i
      (Coalgebra.comul (R := k) (A := F ⊗[k] C) x), ?_⟩
    induction Coalgebra.comul (R := k) (A := F ⊗[k] C) x using
        TensorProduct.induction_on with
    | zero => simp
    | add z w hz hw => simp [hz, hw]
    | tmul z w => rfl
  have himage := htop.map_coalgHom act ⊤
  change IsSubcoalgebra (k := k)
    ((⊤ : Submodule k (F ⊗[k] C)).map act.toLinearMap) at himage
  rw [Submodule.map_top] at himage
  change IsSubcoalgebra (k := k) (LinearMap.range act.toLinearMap) at himage
  convert himage using 1
  apply congrArg LinearMap.range
  apply LinearMap.ext
  intro z
  induction z using TensorProduct.induction_on with
  | zero => simp
  | add x y hx hy => simp [hx, hy]
  | tmul x y => rfl

/-- The finite subcoalgebra obtained by acting with `F` on `C`. -/
def FiniteSubcoalgebra.act
    (F : FiniteSubcoalgebra k H) (C : FiniteSubcoalgebra k M) :
    FiniteSubcoalgebra k M where
  carrier := actionSubspace F.carrier C.carrier
  isSubcoalgebra := F.isSubcoalgebra.actionSubspace C.isSubcoalgebra
  finiteDimensional := finiteDimensional_actionSubspace F.carrier C.carrier

@[simp]
theorem FiniteSubcoalgebra.act_carrier
    (F : FiniteSubcoalgebra k H) (C : FiniteSubcoalgebra k M) :
    (F.act C).carrier = actionSubspace F.carrier C.carrier := rfl

end Coalgebra

section Regular

variable {E : Submodule k H}

/-- For the regular module, the action subspace is the usual product of
submodules. -/
theorem actionSubspace_regular_eq_mul (F E : Submodule k H) :
    actionSubspace F E = F * E := by
  rw [actionSubspace_eq_map₂, Submodule.mul_eq_map₂]
  rfl

end Regular

end

end HopfAmenability
