/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/
import Amenability.LieModuleCoalgebra
import Amenability.SubcoalgebraCoalgebraStruct
import Mathlib.LinearAlgebra.FiniteDimensional.Basic
import Mathlib.LinearAlgebra.TensorProduct.Finiteness
import Mathlib.RingTheory.TensorProduct.Finite

/-!
# Expansion of a subspace under a Lie action
-/

open Module TensorProduct

namespace HopfAmenability

noncomputable section

universe u v w

variable {k : Type u} {L : Type v} {M : Type w}
variable [Field k]
variable [LieRing L] [LieAlgebra k L]
variable [AddCommGroup M] [Module k M]
variable [LieRingModule L M] [LieModule k L M]

/-- The Lie action, regarded as a bilinear map. -/
def lieActionBilinear : L →ₗ[k] M →ₗ[k] M :=
  (LieModule.toEnd k L M : L →ₗ[k] Module.End k M)

/-- The linear map induced by the Lie action on a tensor product. -/
def lieActionMap : L ⊗[k] M →ₗ[k] M :=
  TensorProduct.lift (lieActionBilinear (k := k) (L := L) (M := M))

@[simp]
theorem lieActionMap_tmul (x : L) (m : M) :
    lieActionMap (k := k) (L := L) (M := M) (x ⊗ₜ[k] m) = ⁅x, m⁆ := by
  rfl

/-- The subspace generated by the action of `F` on `E`. -/
def lieActionSubspace (F : Submodule k L) (E : Submodule k M) :
    Submodule k M :=
  Submodule.map₂ (lieActionBilinear (k := k) (L := L) (M := M)) F E

theorem lieActionSubspace_eq_range (F : Submodule k L) (E : Submodule k M) :
    lieActionSubspace F E =
      LinearMap.range
        (lieActionMap (k := k) (L := L) (M := M) ∘ₗ
          TensorProduct.mapIncl F E) := by
  exact TensorProduct.map₂_eq_range_lift_comp_mapIncl _ _ _

/-- A subspace together with its first Lie-action expansion. -/
def lieExpansion (F : Submodule k L) (E : Submodule k M) :
    Submodule k M :=
  E ⊔ lieActionSubspace F E

theorem lieActionSubspace_mono_left {F F' : Submodule k L}
    (h : F ≤ F') (E : Submodule k M) :
    lieActionSubspace F E ≤ lieActionSubspace F' E :=
  Submodule.map₂_le_map₂_left h

theorem lieActionSubspace_mono_right (F : Submodule k L)
    {E E' : Submodule k M} (h : E ≤ E') :
    lieActionSubspace F E ≤ lieActionSubspace F E' :=
  Submodule.map₂_le_map₂_right h

theorem lieExpansion_mono_left {F F' : Submodule k L}
    (h : F ≤ F') (E : Submodule k M) :
    lieExpansion F E ≤ lieExpansion F' E :=
  sup_le_sup_left (lieActionSubspace_mono_left h E) E

theorem lieExpansion_mono_right (F : Submodule k L)
    {E E' : Submodule k M} (h : E ≤ E') :
    lieExpansion F E ≤ lieExpansion F E' :=
  sup_le_sup h (lieActionSubspace_mono_right F h)

theorem le_lieExpansion (F : Submodule k L) (E : Submodule k M) :
    E ≤ lieExpansion F E := le_sup_left

theorem lieActionSubspace_le_lieExpansion
    (F : Submodule k L) (E : Submodule k M) :
    lieActionSubspace F E ≤ lieExpansion F E := le_sup_right

@[simp]
theorem lieExpansion_bot_left (E : Submodule k M) :
    lieExpansion (⊥ : Submodule k L) E = E := by
  simp [lieExpansion, lieActionSubspace]

@[simp]
theorem lieExpansion_bot_right (F : Submodule k L) :
    lieExpansion F (⊥ : Submodule k M) = ⊥ := by
  simp [lieExpansion, lieActionSubspace]

theorem lieActionSubspace_sup_left (F F' : Submodule k L)
    (E : Submodule k M) :
    lieActionSubspace (F ⊔ F') E =
      lieActionSubspace F E ⊔ lieActionSubspace F' E := by
  exact Submodule.map₂_sup_left _ _ _ _

theorem lieExpansion_codimOne_decomposition
    {F' F : Submodule k L} (x : L)
    (hFF : F ≤ F' ⊔ k ∙ x) (E : Submodule k M) :
    lieExpansion F E ≤
      lieExpansion F' E ⊔ lieActionSubspace (k ∙ x) E := by
  apply (lieExpansion_mono_left hFF E).trans
  rw [lieExpansion, lieActionSubspace_sup_left]
  change E ⊔ (lieActionSubspace F' E ⊔ lieActionSubspace (k ∙ x) E) ≤
    (E ⊔ lieActionSubspace F' E) ⊔ lieActionSubspace (k ∙ x) E
  rw [sup_assoc]

theorem finiteDimensional_lieActionSubspace
    (F : Submodule k L) (E : Submodule k M)
    [FiniteDimensional k F] [FiniteDimensional k E] :
    FiniteDimensional k (lieActionSubspace F E) := by
  rw [lieActionSubspace_eq_range]
  infer_instance

theorem finiteDimensional_lieExpansion
    (F : Submodule k L) (E : Submodule k M)
    [FiniteDimensional k F] [FiniteDimensional k E] :
    FiniteDimensional k (lieExpansion F E) := by
  let _ := finiteDimensional_lieActionSubspace F E
  exact Submodule.finiteDimensional_sup E (lieActionSubspace F E)

section Coalgebra

variable [Coalgebra k M] [Coalgebra.LieModuleCoalgebra k L M]

/-- The first Lie expansion of a subcoalgebra is a subcoalgebra. -/
theorem lieExpansion_isSubcoalgebra
    (F : Submodule k L) (C : Submodule k M)
    (hC : IsSubcoalgebra (k := k) C) :
    IsSubcoalgebra (k := k) (lieExpansion F C) := by
  let X := lieExpansion F C
  let stable : Submodule k M :=
    (LinearMap.range (TensorProduct.mapIncl X X)).comap
      (Coalgebra.comul (R := k) (A := M))
  have hCX : C ≤ X := le_lieExpansion F C
  have hCstable : C ≤ stable := by
    intro c hc
    change Coalgebra.comul (R := k) (A := M) c ∈
      LinearMap.range (TensorProduct.mapIncl X X)
    exact TensorProduct.range_mapIncl_mono hCX hCX (hC hc)
  have hactionStable : lieActionSubspace F C ≤ stable := by
    rw [lieActionSubspace]
    apply Submodule.map₂_le.2
    intro x hx c hc
    change Coalgebra.comul (R := k) (A := M) ⁅x, c⁆ ∈
      LinearMap.range (TensorProduct.mapIncl X X)
    rcases hC hc with ⟨z, hz⟩
    let ax : C →ₗ[k] X :=
      LinearMap.codRestrict X
        ((LieModule.toEnd k L M x).comp C.subtype)
        (fun c =>
          (le_sup_right : lieActionSubspace F C ≤ X)
            (Submodule.apply_mem_map₂
              (lieActionBilinear (k := k) (L := L) (M := M)) hx c.2))
    let inc : C →ₗ[k] X :=
      LinearMap.codRestrict X C.subtype (fun c => hCX c.2)
    have hax : ∀ w : C ⊗[k] C,
        TensorProduct.mapIncl X X (TensorProduct.map ax inc w) =
          (LieModule.toEnd k L M x).rTensor M
            (TensorProduct.mapIncl C C w) := by
      intro w
      induction w using TensorProduct.induction_on with
      | zero => simp
      | add z w hz hw => simp [hz, hw]
      | tmul a b => rfl
    have hinc : ∀ w : C ⊗[k] C,
        TensorProduct.mapIncl X X (TensorProduct.map inc ax w) =
          (LieModule.toEnd k L M x).lTensor M
            (TensorProduct.mapIncl C C w) := by
      intro w
      induction w using TensorProduct.induction_on with
      | zero => simp
      | add z w hz hw => simp [hz, hw]
      | tmul a b => rfl
    refine ⟨TensorProduct.map ax inc z + TensorProduct.map inc ax z, ?_⟩
    rw [map_add, Coalgebra.comul_lie_apply, ← hz, hax, hinc]
  exact sup_le hCstable hactionStable

end Coalgebra

end

end HopfAmenability
