/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.LieAmenability
import Amenability.ElementaryLieAlgebra
import Amenability.SubexponentialGrowth

/-!
# Growth conditions for Lie algebras

This file contains the reusable definitions of Lie balls, local finite
dimensionality and Lie growth used by Theorems G--I.
-/

namespace HopfAmenability

noncomputable section

universe u v

variable (k : Type u) [Field k]

/-- Lie balls generated by a coefficient subspace. -/
def lieGrowthBall {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : ℕ → Submodule k L
  | 0 => F
  | n + 1 => lieExpansion F (lieGrowthBall F n)

@[simp]
theorem lieGrowthBall_zero {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : lieGrowthBall k F 0 = F := rfl

@[simp]
theorem lieGrowthBall_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F (n + 1) = lieExpansion F (lieGrowthBall k F n) := rfl

theorem lieGrowthBall_le_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n ≤ lieGrowthBall k F (n + 1) :=
  le_sup_left

theorem lieGrowthBall_mono {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) {m n : ℕ} (hmn : m ≤ n) :
    lieGrowthBall k F m ≤ lieGrowthBall k F n := by
  induction n, hmn using Nat.le_induction with
  | base => exact le_rfl
  | succ n _ ih => exact ih.trans (lieGrowthBall_le_succ k F n)

theorem generator_le_lieGrowthBall {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) (n : ℕ) :
    F ≤ lieGrowthBall k F n :=
  lieGrowthBall_mono k F (Nat.zero_le n)

/-- Lie-growth balls generated by a finite-dimensional coefficient space are
finite-dimensional. -/
theorem finiteDimensional_lieGrowthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F] (n : ℕ) :
    FiniteDimensional k (lieGrowthBall k F n) := by
  induction n with
  | zero =>
      change FiniteDimensional k F
      exact inferInstance
  | succ n ih =>
      rw [lieGrowthBall_succ, lieExpansion]
      let _ : FiniteDimensional k (lieGrowthBall k F n) := ih
      have haction : FiniteDimensional k
          (lieActionSubspace F (lieGrowthBall k F n)) := by
        rw [lieActionSubspace]
        exact Module.Finite.range _
      let _ := haction
      exact inferInstance

theorem lie_bracket_generator_growthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) (x : L) (hx : x ∈ F)
    (y : L) (hy : y ∈ lieGrowthBall k F n) :
    ⁅x, y⁆ ∈ lieGrowthBall k F (n + 1) := by
  rw [lieGrowthBall_succ, lieExpansion]
  apply Submodule.mem_sup_right
  rw [lieActionSubspace_eq_map₂]
  exact Submodule.mem_map₂ _ _ _ hx hy

set_option maxHeartbeats 800000 in
-- Nested bilinear-span elaboration in the Jacobi induction needs extra heartbeats.
/-- Bracketing two Lie-growth balls adds their shifted radii. -/
theorem lie_bracket_growthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (a b : ℕ) (x : L)
    (hx : x ∈ lieGrowthBall k F a) (y : L)
    (hy : y ∈ lieGrowthBall k F b) :
    ⁅x, y⁆ ∈ lieGrowthBall k F (a + b + 1) := by
  induction a generalizing b x y with
  | zero =>
      simpa using lie_bracket_generator_growthBall k F b x hx y hy
  | succ a ih =>
      rw [lieGrowthBall_succ] at hx
      let T : Submodule k L :=
        { carrier := {z | ∀ y ∈ lieGrowthBall k F b,
              ⁅z, y⁆ ∈ lieGrowthBall k F ((a + 1) + b + 1)}
          zero_mem' := by simp
          add_mem' := by
            intro z z' hz hz' y hy
            rw [add_lie]
            exact Submodule.add_mem _ (hz y hy) (hz' y hy)
          smul_mem' := by
            intro r z hz y hy
            rw [smul_lie]
            exact Submodule.smul_mem _ r (hz y hy) }
      have hprev : lieGrowthBall k F a ≤ T := by
        intro z hz y hy
        have hzy : ⁅z, y⁆ ∈ lieGrowthBall k F (a + b + 1) :=
          ih b z hz y hy
        apply lieGrowthBall_mono k F (m := a + b + 1)
        · omega
        · exact hzy
      have haction : lieActionSubspace F (lieGrowthBall k F a) ≤ T := by
        rw [lieActionSubspace_eq_map₂]
        apply Submodule.map₂_le.2
        intro f hf z hz y hy
        change ⁅⁅f, z⁆, y⁆ ∈ _
        rw [lie_lie]
        have hzy : ⁅z, y⁆ ∈ lieGrowthBall k F (a + b + 1) :=
          ih b z hz y hy
        have hfirst0 : ⁅f, ⁅z, y⁆⁆ ∈
            lieGrowthBall k F ((a + b + 1) + 1) :=
          lie_bracket_generator_growthBall k F (a + b + 1) f hf _ hzy
        have hfirst : ⁅f, ⁅z, y⁆⁆ ∈
            lieGrowthBall k F ((a + 1) + b + 1) := by
          rw [show (a + b + 1) + 1 = (a + 1) + b + 1 by omega] at hfirst0
          exact hfirst0
        have hfy : ⁅f, y⁆ ∈ lieGrowthBall k F (b + 1) :=
          lie_bracket_generator_growthBall k F b f hf y hy
        have hsecond0 : ⁅z, ⁅f, y⁆⁆ ∈
            lieGrowthBall k F (a + (b + 1) + 1) :=
          ih (b + 1) z hz _ hfy
        have hsecond : ⁅z, ⁅f, y⁆⁆ ∈
            lieGrowthBall k F ((a + 1) + b + 1) := by
          rw [show a + (b + 1) + 1 = (a + 1) + b + 1 by omega] at hsecond0
          exact hsecond0
        apply Submodule.sub_mem
        · exact hfirst
        · exact hsecond
      have hxT : x ∈ T := (sup_le hprev haction) hx
      exact hxT y hy

/-- The union of the Lie-growth balls, as a linear subspace. -/
def lieGrowthUnion {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : Submodule k L :=
  ⨆ n, lieGrowthBall k F n

theorem lieGrowthBall_le_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n ≤
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  induction n with
  | zero => exact LieSubalgebra.subset_lieSpan
  | succ n ih =>
      rw [lieGrowthBall_succ, lieExpansion, sup_le_iff]
      refine ⟨ih, ?_⟩
      rw [lieActionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x hx y hy
      exact LieSubalgebra.lie_mem _
        (LieSubalgebra.subset_lieSpan hx) (ih hy)

theorem lieGrowthUnion_le_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) :
    lieGrowthUnion k F ≤
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  rw [lieGrowthUnion]
  exact iSup_le fun n ↦ lieGrowthBall_le_lieSpan k F n

/-- The union of the recursive growth balls is the Lie subalgebra generated
by the coefficient space. -/
theorem lieGrowthUnion_eq_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) :
    lieGrowthUnion k F =
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  let U := lieGrowthUnion k F
  let T : LieSubalgebra k L :=
    { carrier := {x | ∀ y ∈ U, ⁅x, y⁆ ∈ U}
      zero_mem' := by simp
      add_mem' := by
        intro x y hx hy z hz
        rw [add_lie]
        exact U.add_mem (hx z hz) (hy z hz)
      smul_mem' := by
        intro r x hx y hy
        rw [smul_lie]
        exact U.smul_mem r (hx y hy)
      lie_mem' := by
        intro x y hx hy z hz
        rw [lie_lie]
        exact U.sub_mem (hx _ (hy z hz)) (hy _ (hx z hz)) }
  have hFT : F ≤ T.toSubmodule := by
    intro x hx y hy
    change y ∈ U at hy
    dsimp [U, lieGrowthUnion] at hy ⊢
    induction hy using Submodule.iSup_induction' with
    | mem n y hy =>
        exact le_iSup (fun m ↦ lieGrowthBall k F m) (n + 1)
          (lie_bracket_generator_growthBall k F n x hx y hy)
    | zero => simp
    | add y z _ _ hy hz => simpa [lie_add] using Submodule.add_mem _ hy hz
  apply le_antisymm
  · exact lieGrowthUnion_le_lieSpan k F
  · have hspanT : LieSubalgebra.lieSpan k L (F : Set L) ≤ T :=
      LieSubalgebra.lieSpan_le.mpr hFT
    intro x hx
    have hxT := hspanT hx
    have hF_U : F ≤ U := by
      intro y hy
      exact le_iSup (fun n ↦ lieGrowthBall k F n) 0 hy
    clear hxT
    induction hx using LieSubalgebra.lieSpan_induction with
    | mem x hx => exact hF_U hx
    | zero => exact U.zero_mem
    | add x y _ _ hx hy => exact U.add_mem hx hy
    | smul r x _ hx => exact U.smul_mem r hx
    | lie x y hxspan _ _ hyU =>
        exact hspanT hxspan y hyU

/-- A Lie algebra is locally finite-dimensional if every finite-dimensional
subspace is contained in a finite-dimensional Lie subalgebra. -/
def IsLocallyFiniteDimensionalLieAlgebra
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ P : Submodule k L, FiniteDimensional k P →
    ∃ S : LieSubalgebra k L,
      P ≤ S.toSubmodule ∧ FiniteDimensional k S

/-- Exponential Lie growth with respect to a finite-dimensional generating
subspace. -/
def HasExponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    Module.Finite k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      ∃ q : ℚ, 1 < q ∧ ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
        q ^ n ≤ (sfinrank k (lieGrowthBall k F n) : ℚ)

/-- Genuine subexponential growth of a finitely generated Lie algebra,
using the manuscript Lie balls (with the documented zero-based shift). -/
def HasSubexponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    FiniteDimensional k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      IsSubexponentialSequence
        (fun n => sfinrank k (lieGrowthBall k F n))

/-- Every finitely generated Lie subalgebra has genuine subexponential
growth. -/
def HasLocallySubexponentialGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ S : LieSubalgebra k L,
    IsFinitelyGeneratedLieAlgebra (k := k) S →
      HasSubexponentialLieGrowth k S

/-- Every finite-dimensional Lie algebra has genuine subexponential
growth. -/
theorem hasSubexponentialLieGrowth_of_finiteDimensional
    {L : Type v} [LieRing L] [LieAlgebra k L]
    [FiniteDimensional k L] :
    HasSubexponentialLieGrowth k L := by
  refine ⟨⊤, inferInstance, ?_, ?_⟩
  · apply top_unique
    intro x _hx
    exact LieSubalgebra.subset_lieSpan (Set.mem_univ x)
  · intro q hq
    let C : ℚ := Module.finrank k L + 1
    have hC : 0 < C := by dsimp [C]; positivity
    refine ⟨C, hC, ?_⟩
    intro n
    have hdim : sfinrank k (lieGrowthBall k (⊤ : Submodule k L) n) ≤
        Module.finrank k L := Submodule.finrank_le _
    have hpow : (1 : ℚ) ≤ q ^ n := one_le_pow₀ hq.le
    calc
      (sfinrank k (lieGrowthBall k (⊤ : Submodule k L) n) : ℚ) ≤
          Module.finrank k L := by exact_mod_cast hdim
      _ ≤ C := by dsimp [C]; linarith
      _ ≤ C * q ^ n := by
        simpa only [mul_one] using mul_le_mul_of_nonneg_left hpow hC.le

/-- In an Abelian Lie algebra every Lie ball is its generating subspace. -/
theorem lieGrowthBall_eq_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L) (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n = F := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [lieGrowthBall_succ, ih, lieExpansion]
      apply sup_eq_left.2
      rw [lieActionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x _hx y _hy
      change ⁅x, y⁆ ∈ F
      rw [hL.trivial x y]
      exact Submodule.zero_mem F

/-- A finitely generated Abelian Lie algebra has genuine subexponential
growth. -/
theorem hasSubexponentialLieGrowth_of_finitelyGenerated_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L)
    (hfg : IsFinitelyGeneratedLieAlgebra (k := k) L) :
    HasSubexponentialLieGrowth k L := by
  obtain ⟨s, hs⟩ := hfg
  let F : Submodule k L := Submodule.span k (s : Set L)
  have hF : FiniteDimensional k F := by
    dsimp [F]
    exact FiniteDimensional.span_of_finite k s.finite_toSet
  refine ⟨F, hF, ?_, ?_⟩
  · apply top_unique
    rw [← hs]
    exact LieSubalgebra.lieSpan_mono Submodule.subset_span
  · intro q hq
    let C : ℚ := Module.finrank k F + 1
    have hC : 0 < C := by dsimp [C]; positivity
    refine ⟨C, hC, ?_⟩
    intro n
    dsimp only
    rw [lieGrowthBall_eq_of_isLieAbelian k hL F n]
    have hpow : (1 : ℚ) ≤ q ^ n := one_le_pow₀ hq.le
    calc
      (sfinrank k F : ℚ) ≤ C := by dsimp [C, sfinrank]; norm_num
      _ ≤ C * q ^ n := by
        simpa only [mul_one] using mul_le_mul_of_nonneg_left hpow hC.le

/-- A Lie subalgebra generated by finitely many elements of an Abelian Lie
algebra is finite-dimensional. -/
theorem finiteDimensional_lieSpan_finset_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L) (s : Finset L) :
    FiniteDimensional k (LieSubalgebra.lieSpan k L (s : Set L)) := by
  have hzero : ∀ᵉ (x ∈ (s : Set L)) (y ∈ (s : Set L)), ⁅x, y⁆ = 0 :=
    fun x _ y _ => hL.trivial x y
  have heq := LieSubalgebra.coe_lieSpan_eq_span_of_forall_lie_eq_zero
    (R := k) (L := L) (s := (s : Set L)) hzero
  let e : LieSubalgebra.lieSpan k L (s : Set L) ≃ₗ[k]
      Submodule.span k (s : Set L) := LinearEquiv.ofEq _ _ heq
  exact FiniteDimensional.of_injective e.toLinearMap e.injective

/-! ## Amenability of locally finite-dimensional Lie algebras -/

/-- The Lie subalgebra generated by a finite set is finitely generated as
an abstract Lie algebra. -/
theorem isFinitelyGeneratedLieAlgebra_lieSpan_finset
    {L : Type v} [LieRing L] [LieAlgebra k L] (s : Finset L) :
    IsFinitelyGeneratedLieAlgebra (k := k)
      (LieSubalgebra.lieSpan k L (s : Set L)) := by
  classical
  let S := LieSubalgebra.lieSpan k L (s : Set L)
  let f : {x // x ∈ s} → S := fun x =>
    ⟨x.1, LieSubalgebra.subset_lieSpan x.2⟩
  let t : Finset S := Finset.univ.image f
  refine ⟨t, ?_⟩
  have ht : (t : Set S) = Set.range f := by
    ext x
    simp [t]
  rw [ht, ← LieSubalgebra.comap_lieSpan_range_eq k S f]
  have hrange : Set.range ((↑) ∘ f) = (s : Set L) := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩
      exact i.2
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  rw [hrange]
  change LieSubalgebra.comap S.incl S = ⊤
  exact (LieSubalgebra.comap_incl_eq_top k S S).mpr le_rfl

/-- Every Abelian Lie algebra is locally of subexponential growth. -/
theorem hasLocallySubexponentialGrowth_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L] (hL : IsLieAbelian L) :
    HasLocallySubexponentialGrowth k L := by
  intro S hSfg
  apply hasSubexponentialLieGrowth_of_finitelyGenerated_of_isLieAbelian
  · exact ⟨fun x y => Subtype.ext (hL.trivial x.1 y.1)⟩
  · exact hSfg

end

end HopfAmenability
