/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.LieAmenability

/-!
# The Lie-algebra generator test

This file separates the manuscript definition of Lie amenability from
algebraic amenability of the regular universal-enveloping module.
-/

open Coalgebra Module

namespace HopfAmenability

noncomputable section

universe u v

variable {k : Type u} {L : Type v}
variable [Field k] [LieRing L] [LieAlgebra k L]

local notation "U" => UniversalEnvelopingAlgebra k L

attribute [local instance 100] LieRing.ofAssociativeRing

/-- Algebraic amenability of the left regular universal-enveloping module. -/
def IsAlgebraicallyAmenableLieAlgebra : Prop :=
  HasActionFolnerSubspaces (k := k) (H := U) (M := U)

/-- Lie amenability as defined in the manuscript.  Only finite-dimensional
subspaces of `L` are tested, and the witnesses are finite subcoalgebras of
`U(L)`.  The acting finite subcoalgebra is exactly `k·1 + ι(F)`, so its
action space is `E + F E`. -/
def IsAmenableLieAlgebra : Prop :=
  ∀ (F : Submodule k L), FiniteDimensional k F →
    ∀ ε : ℚ, 0 < ε →
      ∃ C : FiniteSubcoalgebra k U,
        C.carrier ≠ ⊥ ∧
          (sfinrank k (actionExpansion
              (Submodule.map
                (UniversalEnvelopingAlgebra.ι k).toLinearMap F) C.carrier) : ℚ) ≤
            (1 + ε) * finrank k C.carrier

/-- The unital finite-dimensional coefficient space generated by a Lie test
space. -/
def ueaGeneratorSubspace (F : Submodule k L) : Submodule k U :=
  k ∙ (1 : U) ⊔
    Submodule.map (UniversalEnvelopingAlgebra.ι k).toLinearMap F

theorem finiteDimensional_ueaGeneratorSubspace
    (F : Submodule k L) [FiniteDimensional k F] :
    FiniteDimensional k (ueaGeneratorSubspace (k := k) F) := by
  rw [ueaGeneratorSubspace]
  infer_instance

theorem one_mem_ueaGeneratorSubspace (F : Submodule k L) :
    (1 : U) ∈ ueaGeneratorSubspace (k := k) F :=
  Submodule.mem_sup_left (Submodule.mem_span_singleton_self 1)

theorem ueaGeneratorSubspace_mono {F G : Submodule k L} (hFG : F ≤ G) :
    ueaGeneratorSubspace (k := k) F ≤ ueaGeneratorSubspace (k := k) G :=
  sup_le_sup_left (Submodule.map_mono hFG) _

theorem ueaGeneratorSubspace_pow_le_succ (F : Submodule k L) (n : ℕ) :
    ueaGeneratorSubspace (k := k) F ^ n ≤
      ueaGeneratorSubspace (k := k) F ^ (n + 1) := by
  rw [Submodule.pow_succ]
  intro x hx
  simpa using Submodule.mul_mem_mul hx (one_mem_ueaGeneratorSubspace F)

theorem ueaGeneratorSubspace_pow_mono_nat (F : Submodule k L)
    {m n : ℕ} (hmn : m ≤ n) :
    ueaGeneratorSubspace (k := k) F ^ m ≤
      ueaGeneratorSubspace (k := k) F ^ n := by
  induction n, hmn using Nat.le_induction with
  | base => exact le_rfl
  | succ n hmn ih =>
      exact ih.trans (ueaGeneratorSubspace_pow_le_succ F n)

theorem ueaGeneratorSubspace_pow_mono {F G : Submodule k L}
    (hFG : F ≤ G) (n : ℕ) :
    ueaGeneratorSubspace (k := k) F ^ n ≤
      ueaGeneratorSubspace (k := k) G ^ n := by
  induction n with
  | zero => exact le_rfl
  | succ n ih =>
      rw [Submodule.pow_succ, Submodule.pow_succ]
      apply Submodule.mul_le.2
      intro x hx y hy
      exact Submodule.mul_mem_mul (ih hx)
        (ueaGeneratorSubspace_mono hFG hy)

/-- Elements expressible using a finite-dimensional Lie coefficient space
and a positive bounded word length form a subalgebra of `U(L)`. -/
def ueaFiniteWordSubalgebra : Subalgebra k U where
  carrier := {x | ∃ (F : Submodule k L), FiniteDimensional k F ∧
    ∃ n : ℕ, 0 < n ∧ x ∈ ueaGeneratorSubspace (k := k) F ^ n}
  add_mem' := by
    rintro x y ⟨F, hF, m, hm, hxm⟩ ⟨G, hG, n, hn, hyn⟩
    refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, max m n,
      lt_of_lt_of_le hm (le_max_left _ _), ?_⟩
    apply Submodule.add_mem
    · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_left _ _)
        (ueaGeneratorSubspace_pow_mono le_sup_left m hxm)
    · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_right _ _)
        (ueaGeneratorSubspace_pow_mono le_sup_right n hyn)
  mul_mem' := by
    rintro x y ⟨F, hF, m, hm, hxm⟩ ⟨G, hG, n, hn, hyn⟩
    refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, m + n,
      Nat.add_pos_left hm n, ?_⟩
    rw [Submodule.pow_add (ueaGeneratorSubspace (k := k) (F ⊔ G))
      (Nat.ne_of_gt hn)]
    exact Submodule.mul_mem_mul
      (ueaGeneratorSubspace_pow_mono le_sup_left m hxm)
      (ueaGeneratorSubspace_pow_mono le_sup_right n hyn)
  algebraMap_mem' := by
    intro r
    refine ⟨⊥, inferInstance, 1, Nat.zero_lt_succ 0, ?_⟩
    rw [pow_one]
    have hone := one_mem_ueaGeneratorSubspace (k := k) (⊥ : Submodule k L)
    simpa only [Algebra.smul_def, mul_one] using
      (ueaGeneratorSubspace (k := k) (⊥ : Submodule k L)).smul_mem r hone

theorem ueaFiniteWordSubalgebra_eq_top :
    ueaFiniteWordSubalgebra (k := k) (L := L) = ⊤ := by
  let A := ueaFiniteWordSubalgebra (k := k) (L := L)
  have hi : ∀ x : L, UniversalEnvelopingAlgebra.ι k x ∈ A := by
    intro x
    let F : Submodule k L := k ∙ x
    refine ⟨F, by infer_instance, 1, Nat.zero_lt_succ 0, ?_⟩
    rw [pow_one]
    exact Submodule.mem_sup_right ⟨x,
      Submodule.mem_span_singleton_self x, rfl⟩
  let iA : LieHom k L A :=
    { toLinearMap := (UniversalEnvelopingAlgebra.ι k).toLinearMap.codRestrict
        A.toSubmodule hi
      map_lie' := fun {x y} => by
        apply Subtype.ext
        exact LieHom.map_lie (UniversalEnvelopingAlgebra.ι k) x y }
  let liftA : U →ₐ[k] A := UniversalEnvelopingAlgebra.lift k iA
  have hval : A.val.comp liftA = AlgHom.id k U := by
    apply UniversalEnvelopingAlgebra.hom_ext
    apply DFunLike.ext _ _
    intro x
    change A.val (liftA (UniversalEnvelopingAlgebra.ι k x)) =
      UniversalEnvelopingAlgebra.ι k x
    rw [show liftA (UniversalEnvelopingAlgebra.ι k x) = iA x from
      UniversalEnvelopingAlgebra.lift_ι_apply k iA x]
    rfl
  apply top_unique
  intro x _
  have hx : A.val (liftA x) = x := DFunLike.congr_fun hval x
  rw [← hx]
  exact (liftA x).property

/-- Every element of `U(L)` is contained in a bounded power of a generator
space coming from finitely many Lie elements. -/
theorem exists_mem_ueaGeneratorSubspace_pow (x : U) :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ x ∈ ueaGeneratorSubspace (k := k) F ^ n := by
  have hx : x ∈ ueaFiniteWordSubalgebra (k := k) (L := L) := by
    rw [ueaFiniteWordSubalgebra_eq_top]
    trivial
  exact hx

theorem exists_generator_pow_containing_basis_finset
    {ι : Type*} (b : Basis ι k U) (t : Finset ι) :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ ∀ i ∈ t,
        b i ∈ ueaGeneratorSubspace (k := k) F ^ n := by
  classical
  induction t using Finset.induction_on with
  | empty =>
      refine ⟨⊥, inferInstance, 1, Nat.zero_lt_succ 0, ?_⟩
      simp
  | @insert i t hi ih =>
      obtain ⟨F, hF, m, hm, him⟩ := exists_mem_ueaGeneratorSubspace_pow (b i)
      obtain ⟨G, hG, n, hn, htn⟩ := ih
      refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, max m n,
        lt_of_lt_of_le hm (le_max_left _ _), ?_⟩
      intro j hj
      rw [Finset.mem_insert] at hj
      rcases hj with rfl | hj
      · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_left _ _)
          (ueaGeneratorSubspace_pow_mono le_sup_left m him)
      · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_right _ _)
          (ueaGeneratorSubspace_pow_mono le_sup_right n (htn j hj))

theorem Basis.exists_finset_support_field
    {ι : Type*} (b : Basis ι k U) (P : Submodule k U)
    [FiniteDimensional k P] :
    ∃ t : Finset ι, ∀ x ∈ P, (b.repr x).support ⊆ t := by
  classical
  let e := Module.finBasis k P
  let t : Finset ι := Finset.univ.biUnion fun i =>
    (b.repr (e i : U)).support
  refine ⟨t, ?_⟩
  intro x hx
  let xP : P := ⟨x, hx⟩
  have hxsum : ∑ i, (e.repr xP i) • (e i : U) = x := by
    have h := congrArg P.subtype (e.sum_repr xP)
    rw [map_sum] at h
    simpa using h
  rw [← hxsum, map_sum]
  refine Finsupp.support_finsetSum.trans ?_
  apply Finset.biUnion_subset.2
  intro i hi
  rw [map_smul]
  exact Finsupp.support_smul.trans
    (Finset.subset_biUnion_of_mem
      (fun j => (b.repr (e j : U)).support) (Finset.mem_univ i))

/-- A finite-dimensional subspace of `U(L)` is contained in a bounded power
of a generator space coming from a finite-dimensional subspace of `L`. -/
theorem exists_ueaGeneratorSubspace_pow_containing
    (P : Submodule k U) [FiniteDimensional k P] :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ P ≤ ueaGeneratorSubspace (k := k) F ^ n := by
  classical
  let ι := Module.Basis.ofVectorSpaceIndex k U
  let b : Basis ι k U := Module.Basis.ofVectorSpace k U
  obtain ⟨t, ht⟩ := Basis.exists_finset_support_field (k := k) b P
  obtain ⟨F, hF, n, hn, htn⟩ :=
    exists_generator_pow_containing_basis_finset b t
  refine ⟨F, hF, n, hn, ?_⟩
  intro x hx
  have hsum := b.linearCombination_repr x
  rw [Finsupp.linearCombination_apply] at hsum
  rw [← hsum]
  apply Submodule.sum_mem
  intro i hi
  exact Submodule.smul_mem _ _ (htn i (ht x hx hi))

/-- Multiplying finite-dimensional subspaces cannot have dimension larger
than the product of their dimensions. -/
theorem finrank_submodule_mul_le (P Q : Submodule k U)
    [FiniteDimensional k P] [FiniteDimensional k Q] :
    sfinrank k (P * Q) ≤ sfinrank k P * sfinrank k Q := by
  rw [sfinrank, sfinrank, sfinrank, Submodule.mul_eq_map₂,
    TensorProduct.map₂_eq_range_lift_comp_mapIncl]
  calc
    Module.finrank k ↑(LinearMap.range
        (TensorProduct.lift (LinearMap.mul k U) ∘ₗ
          TensorProduct.mapIncl P Q)) ≤
        Module.finrank k (TensorProduct k P Q) :=
      LinearMap.finrank_range_le
        (TensorProduct.lift (LinearMap.mul k U) ∘ₗ TensorProduct.mapIncl P Q)
    _ = Module.finrank k P * Module.finrank k Q :=
      Module.finrank_tensorProduct

theorem finiteDimensional_submodule_pow (P : Submodule k U)
    [FiniteDimensional k P] (n : ℕ) : FiniteDimensional k ↑(P ^ n) := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero, Submodule.one_eq_span]
      infer_instance
  | succ n hn =>
      rw [Submodule.pow_succ]
      exact finiteDimensional_mul _ _

/-- The powers of a finite-dimensional coefficient space have the expected
elementary dimension bound. -/
theorem finrank_submodule_pow_le (P : Submodule k U)
    [FiniteDimensional k P] (n : ℕ) :
    sfinrank k (P ^ n) ≤ sfinrank k P ^ n := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero]
      rw [sfinrank, Submodule.one_eq_span]
      have hone : (1 : U) ≠ 0 := by
        intro h
        have := congrArg (Coalgebra.counit (R := k)) h
        simp at this
      rw [finrank_span_singleton hone]
      norm_num
  | succ n ih =>
      let _ : FiniteDimensional k ↑(P ^ n) :=
        finiteDimensional_submodule_pow P n
      rw [Submodule.pow_succ, pow_succ]
      exact (finrank_submodule_mul_le (P ^ n) P).trans
        (Nat.mul_le_mul_right _ ih)

/-- A subspace has a complement inside any containing subspace. -/
theorem exists_relative_complement (E V : Submodule k U) (hEV : E ≤ V) :
    ∃ B : Submodule k U, B ≤ V ∧ E ⊔ B = V ∧ E ⊓ B = ⊥ := by
  let E' : Submodule k V := E.comap V.subtype
  obtain ⟨B', hcompl⟩ := E'.exists_isCompl
  let B : Submodule k U := B'.map V.subtype
  refine ⟨B, ?_, ?_, ?_⟩
  · rintro _ ⟨y, _, rfl⟩
    exact y.property
  · have hmap := congrArg (Submodule.map V.subtype) hcompl.sup_eq_top
    rw [Submodule.map_sup, Submodule.map_top,
      Submodule.range_subtype, Submodule.map_comap_subtype,
      inf_eq_right.mpr hEV] at hmap
    exact hmap
  · rw [eq_bot_iff]
    intro x hx
    obtain ⟨y, hyB, rfl⟩ := hx.2
    have hyE' : y ∈ E' := hx.1
    have hy0 : y ∈ (⊥ : Submodule k V) := by
      rw [← hcompl.inf_eq_bot]
      exact ⟨hyE', hyB⟩
    exact congrArg V.subtype (show y = 0 from hy0)

theorem finrank_relative_complement
    (E V B : Submodule k U)
    [FiniteDimensional k E] [FiniteDimensional k V]
    [FiniteDimensional k B]
    (hsup : E ⊔ B = V) (hinf : E ⊓ B = ⊥) :
    sfinrank k V = sfinrank k E + sfinrank k B := by
  have hdim := Submodule.finrank_sup_add_finrank_inf_eq E B
  have hzero : Module.finrank k ↑(⊥ : Submodule k U) = 0 := by simp
  rw [hsup, hinf, hzero, add_zero] at hdim
  simpa only [sfinrank] using hdim

theorem submodule_mul_mono {P P' Q Q' : Submodule k U}
    (hP : P ≤ P') (hQ : Q ≤ Q') : P * Q ≤ P' * Q' := by
  apply Submodule.mul_le.2
  intro x hx y hy
  exact Submodule.mul_mem_mul (hP hx) (hQ hy)

/-- The span of the initial space and the first `n` translates of a boundary
complement. -/
def wordBoundarySpan (V E B : Submodule k U) : ℕ → Submodule k U
  | 0 => E
  | n + 1 => wordBoundarySpan V E B n ⊔ V ^ n * B

theorem pow_mul_le_wordBoundarySpan
    (V E B : Submodule k U)
    (hVE : V * E ≤ E ⊔ B) (n : ℕ) :
    V ^ n * E ≤ wordBoundarySpan V E B n := by
  induction n with
  | zero =>
      simp [wordBoundarySpan]
  | succ n ih =>
      rw [Submodule.pow_succ]
      calc
        (V ^ n * V) * E = V ^ n * (V * E) := mul_assoc _ _ _
        _ ≤ V ^ n * (E ⊔ B) := submodule_mul_mono le_rfl hVE
        _ = V ^ n * E ⊔ V ^ n * B := Submodule.mul_sup _ _ _
        _ ≤ wordBoundarySpan V E B n ⊔ V ^ n * B :=
          sup_le_sup_right ih _
        _ = wordBoundarySpan V E B (n + 1) := rfl

theorem finiteDimensional_wordBoundarySpan
    (V E B : Submodule k U)
    [FiniteDimensional k V] [FiniteDimensional k E]
    [FiniteDimensional k B] (n : ℕ) :
    FiniteDimensional k ↑(wordBoundarySpan V E B n) := by
  induction n with
  | zero => simpa [wordBoundarySpan]
  | succ n hn =>
      rw [wordBoundarySpan]
      let _ : FiniteDimensional k ↑(V ^ n) :=
        finiteDimensional_submodule_pow V n
      let _ : FiniteDimensional k ↑(V ^ n * B) :=
        finiteDimensional_mul _ _
      exact Submodule.finiteDimensional_sup _ _

theorem finrank_sup_le_add (P Q : Submodule k U)
    [FiniteDimensional k P] [FiniteDimensional k Q] :
    sfinrank k (P ⊔ Q) ≤ sfinrank k P + sfinrank k Q := by
  have hdim := Submodule.finrank_sup_add_finrank_inf_eq P Q
  simp only [sfinrank]
  omega

theorem finrank_wordBoundarySpan_le
    (V E B : Submodule k U)
    [FiniteDimensional k V] [FiniteDimensional k E]
    [FiniteDimensional k B] (n : ℕ) :
    sfinrank k (wordBoundarySpan V E B n) ≤
      sfinrank k E +
        (∑ i ∈ Finset.range n, sfinrank k V ^ i) * sfinrank k B := by
  induction n with
  | zero => simp [wordBoundarySpan]
  | succ n ih =>
      let _ : FiniteDimensional k ↑(wordBoundarySpan V E B n) :=
        finiteDimensional_wordBoundarySpan V E B n
      let _ : FiniteDimensional k ↑(V ^ n) :=
        finiteDimensional_submodule_pow V n
      let _ : FiniteDimensional k ↑(V ^ n * B) :=
        finiteDimensional_mul _ _
      calc
        sfinrank k (wordBoundarySpan V E B (n + 1)) =
            sfinrank k (wordBoundarySpan V E B n ⊔ V ^ n * B) := rfl
        _ ≤ sfinrank k (wordBoundarySpan V E B n) +
            sfinrank k (V ^ n * B) := finrank_sup_le_add _ _
        _ ≤ (sfinrank k E +
              (∑ i ∈ Finset.range n, sfinrank k V ^ i) * sfinrank k B) +
            (sfinrank k V ^ n) * sfinrank k B := by
          gcongr
          exact (finrank_submodule_mul_le (V ^ n) B).trans
            (Nat.mul_le_mul_right _ (finrank_submodule_pow_le V n))
        _ = sfinrank k E +
            (∑ i ∈ Finset.range (n + 1), sfinrank k V ^ i) *
              sfinrank k B := by
          rw [Finset.sum_range_succ]
          ring

/-- The hard direction of the generator test: a Følner subcoalgebra for a
finite Lie-generator space controls every bounded word space in `U(L)`. -/
theorem IsAmenableLieAlgebra.isAlgebraicallyAmenable
    (hL : IsAmenableLieAlgebra (k := k) (L := L)) :
    IsAlgebraicallyAmenableLieAlgebra (k := k) (L := L) := by
  intro P hP ε hε
  let _ : FiniteDimensional k P := hP
  obtain ⟨F, hF, n, hn, hPpow⟩ :=
    exists_ueaGeneratorSubspace_pow_containing P
  let _ : FiniteDimensional k F := hF
  let V := ueaGeneratorSubspace (k := k) F
  let _ : FiniteDimensional k V := finiteDimensional_ueaGeneratorSubspace F
  let S : ℕ := ∑ i ∈ Finset.range n, sfinrank k V ^ i
  have hSpos : 0 < S := by
    have hzero : 0 ∈ Finset.range n := Finset.mem_range.mpr hn
    have hone : 0 < sfinrank k V ^ 0 := by simp
    exact lt_of_lt_of_le hone (Finset.single_le_sum
      (fun _ _ => Nat.zero_le _) hzero)
  let δ : ℚ := ε / (S : ℚ)
  have hδ : 0 < δ := div_pos hε (by exact_mod_cast hSpos)
  obtain ⟨C, hC, hCratio⟩ := hL F hF δ hδ
  let E : Submodule k U := C.carrier
  let _ : FiniteDimensional k E := C.finiteDimensional
  have hVE : E ≤ V * E := by
    intro x hx
    have hm := Submodule.mul_mem_mul (one_mem_ueaGeneratorSubspace F) hx
    simpa using hm
  obtain ⟨B, hBVE, hEB, hEinfB⟩ := exists_relative_complement E (V * E) hVE
  let _ : FiniteDimensional k (V * E) := finiteDimensional_mul V E
  let _ : FiniteDimensional k B :=
    FiniteDimensional.of_injective (Submodule.inclusion hBVE)
      (Submodule.inclusion_injective hBVE)
  have hdimVE : sfinrank k (V * E) = sfinrank k E + sfinrank k B :=
    finrank_relative_complement E (V * E) B hEB hEinfB
  have hratioVE : (sfinrank k (V * E) : ℚ) ≤
      (1 + δ) * sfinrank k E := by
    have hVeq : V =
        (Submodule.map (UniversalEnvelopingAlgebra.ι k).toLinearMap F) ⊔
          (unitFiniteSubcoalgebra (k := k) (H := U)).carrier := by
      dsimp [V, ueaGeneratorSubspace]
      rw [sup_comm]
      rfl
    rw [← actionSubspace_regular_eq_mul, hVeq,
      actionSubspace_sup_unit_eq_actionExpansion]
    exact hCratio
  have hBbound : (sfinrank k B : ℚ) ≤ δ * sfinrank k E := by
    rw [hdimVE] at hratioVE
    push_cast at hratioVE
    linarith
  let W := wordBoundarySpan V E B n
  let _ : FiniteDimensional k W := finiteDimensional_wordBoundarySpan V E B n
  have hPE : actionExpansion P E ≤ W := by
    apply sup_le
    · have hE0 : E ≤ V ^ n * E := by
        intro x hx
        have hone0 : (1 : U) ∈ V ^ 0 := by
          rw [Submodule.pow_zero]
          exact Submodule.mem_one.mpr ⟨1, map_one (algebraMap k U)⟩
        have hone : (1 : U) ∈ V ^ n :=
          ueaGeneratorSubspace_pow_mono_nat F (Nat.zero_le n) hone0
        have hm := Submodule.mul_mem_mul hone hx
        simpa using hm
      exact hE0.trans (pow_mul_le_wordBoundarySpan V E B
        (by rw [hEB]) n)
    · rw [actionSubspace_regular_eq_mul]
      exact (submodule_mul_mono hPpow le_rfl).trans
        (pow_mul_le_wordBoundarySpan V E B
          (by rw [hEB]) n)
  refine ⟨E, hC, inferInstance, ?_⟩
  have hdim := Submodule.finrank_mono hPE
  have hWbound := finrank_wordBoundarySpan_le V E B n
  have hSE : (S : ℚ) * sfinrank k B ≤ ε * sfinrank k E := by
    calc
      (S : ℚ) * sfinrank k B ≤ (S : ℚ) * (δ * sfinrank k E) :=
        mul_le_mul_of_nonneg_left hBbound (by positivity)
      _ = ε * sfinrank k E := by
        change (S : ℚ) * ((ε / (S : ℚ)) * sfinrank k E) = _
        field_simp
  calc
    (sfinrank k (actionExpansion P E) : ℚ) ≤ sfinrank k W := by
      exact_mod_cast hdim
    _ ≤ sfinrank k E + S * sfinrank k B := by exact_mod_cast hWbound
    _ ≤ sfinrank k E + ε * sfinrank k E := by
      simpa only [add_comm] using add_le_add_left hSE (sfinrank k E : ℚ)
    _ = (1 + ε) * sfinrank k E := by ring

/-- Algebraic amenability immediately implies manuscript Lie amenability by
rounding and restricting the acting test space to `k·1 + ι(F)`. -/
theorem IsAlgebraicallyAmenableLieAlgebra.isAmenableLieAlgebra
    (hL : IsAlgebraicallyAmenableLieAlgebra (k := k) (L := L)) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  have hcoal : IsAmenableHopfModuleCoalgebra (k := k) (H := U) (M := U) :=
    HasActionFolnerSubspaces.isAmenableHopfModuleCoalgebra hL
  rw [IsAmenableLieAlgebra]
  intro F hF
  let _ : FiniteDimensional k F := hF
  intro ε hε
  exact hcoal
    (Submodule.map (UniversalEnvelopingAlgebra.ι k).toLinearMap F)
    (by infer_instance) ε hε

/-- **Generator test.** Manuscript Lie amenability is equivalent to algebraic
amenability of the regular universal-enveloping module. -/
theorem isAmenableLieAlgebra_iff_algebraicallyAmenable :
    IsAmenableLieAlgebra (k := k) (L := L) ↔
      IsAlgebraicallyAmenableLieAlgebra (k := k) (L := L) :=
  ⟨IsAmenableLieAlgebra.isAlgebraicallyAmenable,
    IsAlgebraicallyAmenableLieAlgebra.isAmenableLieAlgebra⟩

/-- Compatibility name emphasizing the regular-action Følner formulation. -/
theorem isAmenableLieAlgebra_iff_regularActionFolner :
    IsAmenableLieAlgebra (k := k) (L := L) ↔
      HasActionFolnerSubspaces (k := k) (H := U) (M := U) :=
  isAmenableLieAlgebra_iff_algebraicallyAmenable

end

end HopfAmenability
