/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.TheoremD
import Amenability.AscendingFiltrationBasis
import Amenability.WeightedPBWGrowth

/-!
# Growth conditions for Lie algebras

This file contains the reusable definitions of Lie balls, local finite
dimensionality and Lie growth used by Theorems G--I.
-/

namespace HopfAmenability

noncomputable section

universe u v

variable (k : Type u) [Field k]

/-- Lie balls generated by a coefficient subspace. -/
def lieGrowthBall {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : ℕ → Submodule k L
  | 0 => F
  | n + 1 => lieExpansion F (lieGrowthBall F n)

@[simp]
theorem lieGrowthBall_zero {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : lieGrowthBall k F 0 = F := rfl

@[simp]
theorem lieGrowthBall_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F (n + 1) = lieExpansion F (lieGrowthBall k F n) := rfl

theorem lieGrowthBall_le_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n ≤ lieGrowthBall k F (n + 1) :=
  le_sup_left

theorem lieGrowthBall_mono {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) {m n : ℕ} (hmn : m ≤ n) :
    lieGrowthBall k F m ≤ lieGrowthBall k F n := by
  induction n, hmn using Nat.le_induction with
  | base => exact le_rfl
  | succ n _ ih => exact ih.trans (lieGrowthBall_le_succ k F n)

theorem generator_le_lieGrowthBall {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) (n : ℕ) :
    F ≤ lieGrowthBall k F n :=
  lieGrowthBall_mono k F (Nat.zero_le n)

/-- Lie-growth balls generated by a finite-dimensional coefficient space are
finite-dimensional. -/
theorem finiteDimensional_lieGrowthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F] (n : ℕ) :
    FiniteDimensional k (lieGrowthBall k F n) := by
  induction n with
  | zero =>
      change FiniteDimensional k F
      exact inferInstance
  | succ n ih =>
      rw [lieGrowthBall_succ, lieExpansion]
      let _ : FiniteDimensional k (lieGrowthBall k F n) := ih
      have haction : FiniteDimensional k
          (lieActionSubspace F (lieGrowthBall k F n)) := by
        rw [lieActionSubspace]
        exact Module.Finite.range _
      let _ := haction
      exact inferInstance

theorem lie_bracket_generator_growthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) (x : L) (hx : x ∈ F)
    (y : L) (hy : y ∈ lieGrowthBall k F n) :
    ⁅x, y⁆ ∈ lieGrowthBall k F (n + 1) := by
  rw [lieGrowthBall_succ, lieExpansion]
  apply Submodule.mem_sup_right
  rw [lieActionSubspace_eq_map₂]
  exact Submodule.mem_map₂ _ _ _ hx hy

set_option maxHeartbeats 800000 in
-- Nested bilinear-span elaboration in the Jacobi induction needs extra heartbeats.
/-- Bracketing two Lie-growth balls adds their shifted radii. -/
theorem lie_bracket_growthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (a b : ℕ) (x : L)
    (hx : x ∈ lieGrowthBall k F a) (y : L)
    (hy : y ∈ lieGrowthBall k F b) :
    ⁅x, y⁆ ∈ lieGrowthBall k F (a + b + 1) := by
  induction a generalizing b x y with
  | zero =>
      simpa using lie_bracket_generator_growthBall k F b x hx y hy
  | succ a ih =>
      rw [lieGrowthBall_succ] at hx
      let T : Submodule k L :=
        { carrier := {z | ∀ y ∈ lieGrowthBall k F b,
              ⁅z, y⁆ ∈ lieGrowthBall k F ((a + 1) + b + 1)}
          zero_mem' := by simp
          add_mem' := by
            intro z z' hz hz' y hy
            rw [add_lie]
            exact Submodule.add_mem _ (hz y hy) (hz' y hy)
          smul_mem' := by
            intro r z hz y hy
            rw [smul_lie]
            exact Submodule.smul_mem _ r (hz y hy) }
      have hprev : lieGrowthBall k F a ≤ T := by
        intro z hz y hy
        have hzy : ⁅z, y⁆ ∈ lieGrowthBall k F (a + b + 1) :=
          ih b z hz y hy
        apply lieGrowthBall_mono k F (m := a + b + 1)
        · omega
        · exact hzy
      have haction : lieActionSubspace F (lieGrowthBall k F a) ≤ T := by
        rw [lieActionSubspace_eq_map₂]
        apply Submodule.map₂_le.2
        intro f hf z hz y hy
        change ⁅⁅f, z⁆, y⁆ ∈ _
        rw [lie_lie]
        have hzy : ⁅z, y⁆ ∈ lieGrowthBall k F (a + b + 1) :=
          ih b z hz y hy
        have hfirst0 : ⁅f, ⁅z, y⁆⁆ ∈
            lieGrowthBall k F ((a + b + 1) + 1) :=
          lie_bracket_generator_growthBall k F (a + b + 1) f hf _ hzy
        have hfirst : ⁅f, ⁅z, y⁆⁆ ∈
            lieGrowthBall k F ((a + 1) + b + 1) := by
          rw [show (a + b + 1) + 1 = (a + 1) + b + 1 by omega] at hfirst0
          exact hfirst0
        have hfy : ⁅f, y⁆ ∈ lieGrowthBall k F (b + 1) :=
          lie_bracket_generator_growthBall k F b f hf y hy
        have hsecond0 : ⁅z, ⁅f, y⁆⁆ ∈
            lieGrowthBall k F (a + (b + 1) + 1) :=
          ih (b + 1) z hz _ hfy
        have hsecond : ⁅z, ⁅f, y⁆⁆ ∈
            lieGrowthBall k F ((a + 1) + b + 1) := by
          rw [show a + (b + 1) + 1 = (a + 1) + b + 1 by omega] at hsecond0
          exact hsecond0
        apply Submodule.sub_mem
        · exact hfirst
        · exact hsecond
      have hxT : x ∈ T := (sup_le hprev haction) hx
      exact hxT y hy

/-- The union of the Lie-growth balls, as a linear subspace. -/
def lieGrowthUnion {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : Submodule k L :=
  ⨆ n, lieGrowthBall k F n

theorem lieGrowthBall_le_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n ≤
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  induction n with
  | zero => exact LieSubalgebra.subset_lieSpan
  | succ n ih =>
      rw [lieGrowthBall_succ, lieExpansion, sup_le_iff]
      refine ⟨ih, ?_⟩
      rw [lieActionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x hx y hy
      exact LieSubalgebra.lie_mem _
        (LieSubalgebra.subset_lieSpan hx) (ih hy)

theorem lieGrowthUnion_le_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) :
    lieGrowthUnion k F ≤
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  rw [lieGrowthUnion]
  exact iSup_le fun n ↦ lieGrowthBall_le_lieSpan k F n

/-- The union of the recursive growth balls is the Lie subalgebra generated
by the coefficient space. -/
theorem lieGrowthUnion_eq_lieSpan {L : Type v}
    [LieRing L] [LieAlgebra k L] (F : Submodule k L) :
    lieGrowthUnion k F =
      (LieSubalgebra.lieSpan k L (F : Set L)).toSubmodule := by
  let U := lieGrowthUnion k F
  let T : LieSubalgebra k L :=
    { carrier := {x | ∀ y ∈ U, ⁅x, y⁆ ∈ U}
      zero_mem' := by simp
      add_mem' := by
        intro x y hx hy z hz
        rw [add_lie]
        exact U.add_mem (hx z hz) (hy z hz)
      smul_mem' := by
        intro r x hx y hy
        rw [smul_lie]
        exact U.smul_mem r (hx y hy)
      lie_mem' := by
        intro x y hx hy z hz
        rw [lie_lie]
        exact U.sub_mem (hx _ (hy z hz)) (hy _ (hx z hz)) }
  have hFT : F ≤ T.toSubmodule := by
    intro x hx y hy
    change y ∈ U at hy
    dsimp [U, lieGrowthUnion] at hy ⊢
    induction hy using Submodule.iSup_induction' with
    | mem n y hy =>
        exact le_iSup (fun m ↦ lieGrowthBall k F m) (n + 1)
          (lie_bracket_generator_growthBall k F n x hx y hy)
    | zero => simp
    | add y z _ _ hy hz => simpa [lie_add] using Submodule.add_mem _ hy hz
  apply le_antisymm
  · exact lieGrowthUnion_le_lieSpan k F
  · have hspanT : LieSubalgebra.lieSpan k L (F : Set L) ≤ T :=
      LieSubalgebra.lieSpan_le.mpr hFT
    intro x hx
    have hxT := hspanT hx
    have hF_U : F ≤ U := by
      intro y hy
      exact le_iSup (fun n ↦ lieGrowthBall k F n) 0 hy
    clear hxT
    induction hx using LieSubalgebra.lieSpan_induction with
    | mem x hx => exact hF_U hx
    | zero => exact U.zero_mem
    | add x y _ _ hx hy => exact U.add_mem hx hy
    | smul r x _ hx => exact U.smul_mem r hx
    | lie x y hxspan _ _ hyU =>
        exact hspanT hxspan y hyU

/-- The index type of the basis adapted to the Lie-growth balls. -/
abbrev LieGrowthBasisIndex {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) :=
  AscendingBasisIndex (k := k) (lieGrowthBall k F)

/-- The exhaustive Lie-ball filtration has a basis graded by first
appearance in the filtration. -/
def lieGrowthBasis {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L)
    (hspan : LieSubalgebra.lieSpan k L (F : Set L) = ⊤) :
    Module.Basis (LieGrowthBasisIndex k F) k L :=
  ascendingFiltrationBasis (k := k) (lieGrowthBall k F)
    (fun _ _ h ↦ lieGrowthBall_mono k F h)
    (by
      change lieGrowthUnion k F = ⊤
      rw [lieGrowthUnion_eq_lieSpan, hspan]
      rfl)

/-- The shifted filtration degree of an adapted Lie-growth basis vector. -/
def lieGrowthBasisWeight {L : Type v} [LieRing L] [LieAlgebra k L]
    {F : Submodule k L} (i : LieGrowthBasisIndex k F) : ℕ :=
  i.1 + 1

theorem lieGrowthBasis_mem_growthBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L)
    (hspan : LieSubalgebra.lieSpan k L (F : Set L) = ⊤)
    (i : LieGrowthBasisIndex k F) :
    lieGrowthBasis k F hspan i ∈ lieGrowthBall k F i.1 :=
  ascendingFiltrationBasis_mem (k := k) (lieGrowthBall k F)
    (fun _ _ h ↦ lieGrowthBall_mono k F h)
    (by
      change lieGrowthUnion k F = ⊤
      rw [lieGrowthUnion_eq_lieSpan, hspan]
      rfl) i

/-- Lie brackets are compatible with the shifted degree on the adapted
Lie-growth basis. -/
theorem lieGrowthBasis_bracketWeightCompatible
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L)
    (hspan : LieSubalgebra.lieSpan k L (F : Set L) = ⊤)
    [LinearOrder (LieGrowthBasisIndex k F)] :
    UniversalEnvelopingAlgebra.BracketWeightCompatible
      (lieGrowthBasis k F hspan)
        (lieGrowthBasisWeight (k := k) (F := F)) := by
  intro i j l hl
  let b := lieGrowthBasis k F hspan
  have hbracket : ⁅b i, b j⁆ ∈ lieGrowthBall k F (i.1 + j.1 + 1) :=
    lie_bracket_growthBall k F i.1 j.1 (b i)
      (lieGrowthBasis_mem_growthBall k F hspan i) (b j)
      (lieGrowthBasis_mem_growthBall k F hspan j)
  have hspanbelow : Submodule.span k
      (b '' ascendingBasisBelow (k := k) (lieGrowthBall k F)
        (i.1 + j.1 + 1)) = lieGrowthBall k F (i.1 + j.1 + 1) :=
    span_ascendingBasisBelow_eq (k := k) (lieGrowthBall k F)
      (fun _ _ h ↦ lieGrowthBall_mono k F h)
      (by
        change lieGrowthUnion k F = ⊤
        rw [lieGrowthUnion_eq_lieSpan, hspan]
        rfl) _
  have hsupport := b.repr_support_subset_of_mem_span
    (ascendingBasisBelow (k := k) (lieGrowthBall k F)
      (i.1 + j.1 + 1)) (hspanbelow.symm ▸ hbracket)
  have hlDegree := hsupport hl
  change l.1 + 1 ≤ (i.1 + 1) + (j.1 + 1)
  change l.1 ≤ i.1 + j.1 + 1 at hlDegree
  omega

/-- Forgetting the positive shift sends a bounded weight sublevel into the
corresponding bounded-degree adapted-basis index. -/
def lieGrowthWeightSublevelToBelow
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    UniversalEnvelopingAlgebra.WeightSublevel
        (lieGrowthBasisWeight (k := k) (F := F)) n →
      AscendingBasisBelowIndex (k := k) (lieGrowthBall k F) n :=
  fun i ↦ ⟨i.1, by
    have hi := i.2
    change i.1.1 + 1 ≤ n at hi
    omega⟩

theorem lieGrowthWeightSublevelToBelow_injective
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    Function.Injective (lieGrowthWeightSublevelToBelow k F n) := by
  intro i j hij
  apply Subtype.ext
  exact congrArg
    (fun z : AscendingBasisBelowIndex (k := k) (lieGrowthBall k F) n ↦ z.1)
    hij

/-- Every bounded sublevel of the shifted Lie-growth weight is finite. -/
@[instance_reducible]
noncomputable def fintypeLieGrowthWeightSublevel
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F] (n : ℕ) :
    Fintype (UniversalEnvelopingAlgebra.WeightSublevel
      (lieGrowthBasisWeight (k := k) (F := F)) n) := by
  let hfinite : ∀ r, FiniteDimensional k (lieGrowthBall k F r) :=
    fun r ↦ finiteDimensional_lieGrowthBall k F r
  letI : Fintype (AscendingBasisBelowIndex (k := k)
      (lieGrowthBall k F) n) :=
    fintypeAscendingBasisBelowIndex (k := k) (lieGrowthBall k F) n hfinite
  exact Fintype.ofInjective (lieGrowthWeightSublevelToBelow k F n)
    (lieGrowthWeightSublevelToBelow_injective k F n)

set_option linter.style.haveILetI false in
-- The local finite instances are the chosen instances occurring in the statement.
/-- The number of adapted Lie-basis letters of weight at most `n` is bounded
by the dimension of the `n`th Lie-growth ball. -/
theorem card_lieGrowthWeightSublevel_le
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F] (n : ℕ) :
    @Fintype.card
        (UniversalEnvelopingAlgebra.WeightSublevel
          (lieGrowthBasisWeight (k := k) (F := F)) n)
        (fintypeLieGrowthWeightSublevel k F n) ≤
      sfinrank k (lieGrowthBall k F n) := by
  let hfinite : ∀ r, FiniteDimensional k (lieGrowthBall k F r) :=
    fun r ↦ finiteDimensional_lieGrowthBall k F r
  letI : Fintype (UniversalEnvelopingAlgebra.WeightSublevel
      (lieGrowthBasisWeight (k := k) (F := F)) n) :=
    fintypeLieGrowthWeightSublevel k F n
  letI : Fintype (AscendingBasisBelowIndex (k := k)
      (lieGrowthBall k F) n) :=
    fintypeAscendingBasisBelowIndex (k := k) (lieGrowthBall k F) n hfinite
  calc
    Fintype.card (UniversalEnvelopingAlgebra.WeightSublevel
        (lieGrowthBasisWeight (k := k) (F := F)) n) ≤
        Fintype.card (AscendingBasisBelowIndex (k := k)
          (lieGrowthBall k F) n) :=
      Fintype.card_le_of_injective _
        (lieGrowthWeightSublevelToBelow_injective k F n)
    _ = sfinrank k (lieGrowthBall k F n) := by
      exact card_ascendingBasisBelowIndex (k := k) (lieGrowthBall k F)
        (fun _ _ h ↦ lieGrowthBall_mono k F h) n hfinite

/-- A Lie algebra is locally finite-dimensional if every finite-dimensional
subspace is contained in a finite-dimensional Lie subalgebra. -/
def IsLocallyFiniteDimensionalLieAlgebra
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ P : Submodule k L, FiniteDimensional k P →
    ∃ S : LieSubalgebra k L,
      P ≤ S.toSubmodule ∧ FiniteDimensional k S

/-- Exponential Lie growth with respect to a finite-dimensional generating
subspace. -/
def HasExponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    Module.Finite k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      ∃ q : ℚ, 1 < q ∧ ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
        q ^ n ≤ (sfinrank k (lieGrowthBall k F n) : ℚ)

/-- A natural-valued sequence has subexponential growth if it is bounded by
every rational exponential rate greater than one, up to a positive
multiplicative constant. -/
def IsSubexponentialSequence (a : ℕ → ℕ) : Prop :=
  ∀ q : ℚ, 1 < q →
    ∃ C : ℚ, 0 < C ∧ ∀ n : ℕ, (a n : ℚ) ≤ C * q ^ n

/-- On `[0,1]`, the binomial expansion is bounded linearly with the sum of
its nonconstant coefficients. -/
theorem one_add_pow_le_one_add_two_pow_sub_one_mul
    (x : ℚ) (hx0 : 0 ≤ x) (hx1 : x ≤ 1) : ∀ n : ℕ,
    (1 + x) ^ n ≤ 1 + ((2 : ℚ) ^ n - 1) * x := by
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [pow_succ, pow_succ]
      have hbase : 0 ≤ 1 + x := by linarith
      have hmul := mul_le_mul_of_nonneg_right ih hbase
      have hxx : x * x ≤ x := by nlinarith
      calc
        (1 + x) ^ n * (1 + x) ≤
            (1 + (2 ^ n - 1) * x) * (1 + x) := hmul
        _ ≤ 1 + (2 ^ n * 2 - 1) * x := by
          have hp : (1 : ℚ) ≤ 2 ^ n := one_le_pow₀ (by norm_num)
          nlinarith

/-- Sampling a subexponential sequence along a fixed arithmetic dilation
preserves subexponential growth. -/
theorem IsSubexponentialSequence.comp_mul (a : ℕ → ℕ)
    (ha : IsSubexponentialSequence a) (d : ℕ) :
    IsSubexponentialSequence (fun n => a (d * n)) := by
  intro q hq
  by_cases hd : d = 0
  · subst d
    obtain ⟨C, hC, h⟩ := ha q hq
    refine ⟨C, hC, fun n => ?_⟩
    calc
      (a (0 * n) : ℚ) = a 0 := by simp
      _ ≤ C := by simpa using h 0
      _ ≤ C * q ^ n := by
        simpa only [mul_one] using mul_le_mul_of_nonneg_left
          (one_le_pow₀ hq.le) hC.le
  · have hdpos : 0 < d := Nat.pos_of_ne_zero hd
    let x : ℚ := (q - 1) / ((2 : ℚ) ^ d * q ^ d)
    have hq0 : 0 < q := by linarith
    have hden : 0 < (2 : ℚ) ^ d * q ^ d :=
      mul_pos (by positivity) (by positivity)
    have hx0 : 0 < x := div_pos (sub_pos.mpr hq) hden
    have hqd : q ≤ q ^ d := by
      have := pow_le_pow_right₀ hq.le (show 1 ≤ d by omega)
      simpa using this
    have hx1 : x ≤ 1 := by
      rw [div_le_one hden]
      have htwo : (1 : ℚ) ≤ 2 ^ d := one_le_pow₀ (by norm_num)
      have := mul_le_mul htwo hqd (by positivity) (by norm_num)
      nlinarith
    let r : ℚ := 1 + x
    have hr : 1 < r := by dsimp [r]; linarith
    obtain ⟨C, hC, hbound⟩ := ha r hr
    refine ⟨C, hC, fun n => ?_⟩
    have hrd : r ^ d ≤ q := by
      have hp := one_add_pow_le_one_add_two_pow_sub_one_mul
        x hx0.le hx1 d
      have hcoef : ((2 : ℚ) ^ d - 1) * x ≤ q - 1 := by
        dsimp [x]
        rw [div_eq_mul_inv]
        have hpow2 : 0 ≤ (2 : ℚ) ^ d := pow_nonneg (by norm_num) _
        have hqpow : 1 ≤ q ^ d := one_le_pow₀ hq.le
        rw [show ((2 : ℚ) ^ d - 1) *
            ((q - 1) * ((2 : ℚ) ^ d * q ^ d)⁻¹) =
          (((2 : ℚ) ^ d - 1) * (q - 1)) /
            ((2 : ℚ) ^ d * q ^ d) by ring]
        rw [div_le_iff₀ hden]
        have hcoef2 : (2 : ℚ) ^ d - 1 ≤ 2 ^ d := by linarith
        have hmul := mul_le_mul_of_nonneg_right hcoef2 (sub_pos.mpr hq).le
        have hqd1 : 1 ≤ q ^ d := one_le_pow₀ hq.le
        nlinarith [mul_le_mul_of_nonneg_left hqd1
          (mul_nonneg hpow2 (sub_pos.mpr hq).le)]
      dsimp [r]
      linarith
    calc
      (a (d * n) : ℚ) ≤ C * r ^ (d * n) := hbound (d * n)
      _ = C * (r ^ d) ^ n := by rw [pow_mul]
      _ ≤ C * q ^ n := by
        exact mul_le_mul_of_nonneg_left
          (pow_le_pow_left₀ (by positivity) hrd n) hC.le

/-- Genuine subexponential growth of a finitely generated Lie algebra,
using the manuscript Lie balls (with the documented zero-based shift). -/
def HasSubexponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    FiniteDimensional k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      IsSubexponentialSequence
        (fun n => sfinrank k (lieGrowthBall k F n))

/-- Every finitely generated Lie subalgebra has genuine subexponential
growth. -/
def HasLocallySubexponentialGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ S : LieSubalgebra k L,
    IsFinitelyGeneratedLieAlgebra (k := k) S →
      HasSubexponentialLieGrowth k S

/-- The unital left-multiplication balls of an associative algebra. -/
def associativeGrowthBall
    {A : Type v} [Ring A] [Algebra k A]
    (P : Submodule k A) : ℕ → Submodule k A
  | 0 => k ∙ (1 : A)
  | n + 1 => associativeGrowthBall P n ⊔ P * associativeGrowthBall P n

/-- Subexponential growth of every finite-dimensional coefficient
filtration of an associative algebra. -/
def HasSubexponentialAlgebraGrowth
    {A : Type v} [Ring A] [Algebra k A] : Prop :=
  ∀ P : Submodule k A, FiniteDimensional k P →
    IsSubexponentialSequence
      (fun n => sfinrank k (associativeGrowthBall k P n))

set_option linter.style.haveILetI false in
/-- The weighted PBW filtration attached to a subexponential Lie-growth
basis has subexponential dimension. -/
theorem isSubexponentialSequence_lieGrowthPBWFiltration
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F]
    (hspan : LieSubalgebra.lieSpan k L (F : Set L) = ⊤)
    (hsub : IsSubexponentialSequence
      (fun n => sfinrank k (lieGrowthBall k F n)))
    [LinearOrder (LieGrowthBasisIndex k F)]
    [Nonempty (LieGrowthBasisIndex k F)] :
    IsSubexponentialSequence (fun n => sfinrank k
      (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
        (lieGrowthBasis k F hspan)
        (lieGrowthBasisWeight (k := k) (F := F)) n)) := by
  let weight := lieGrowthBasisWeight (k := k) (F := F)
  let b := lieGrowthBasis k F hspan
  have hfinite : ∀ n,
      Finite (UniversalEnvelopingAlgebra.WeightSublevel weight n) := by
    intro n
    exact @Finite.of_fintype _ (fintypeLieGrowthWeightSublevel k F n)
  have hcount : ∀ r : ℚ, 1 < r → ∃ C : ℚ, 0 < C ∧ ∀ m,
      (Nat.card (UniversalEnvelopingAlgebra.WeightSublevel weight m) : ℚ) ≤
        C * r ^ m := by
    intro r hr
    obtain ⟨C, hC, hball⟩ := hsub r hr
    refine ⟨C, hC, fun m => ?_⟩
    let _ : Fintype (UniversalEnvelopingAlgebra.WeightSublevel weight m) :=
      fintypeLieGrowthWeightSublevel k F m
    calc
      (Nat.card (UniversalEnvelopingAlgebra.WeightSublevel weight m) : ℚ) =
          Fintype.card (UniversalEnvelopingAlgebra.WeightSublevel weight m) := by
        rw [Nat.card_eq_fintype_card]
      _ ≤ sfinrank k (lieGrowthBall k F m) := by
        exact_mod_cast card_lieGrowthWeightSublevel_le k F m
      _ ≤ C * r ^ m := hball m
  have hwords := UniversalEnvelopingAlgebra.boundedWeightPBWWord_subexponential
    weight (fun i => by dsimp [weight, lieGrowthBasisWeight]; omega)
    hfinite hcount
  intro q hq
  obtain ⟨D, hD, hbound⟩ := hwords q hq
  refine ⟨D, hD, fun n => ?_⟩
  letI : Fintype (UniversalEnvelopingAlgebra.WeightSublevel weight n) :=
    fintypeLieGrowthWeightSublevel k F n
  letI : Fintype
      (UniversalEnvelopingAlgebra.BoundedWeightPBWWord weight n) :=
    UniversalEnvelopingAlgebra.fintypeBoundedWeightPBWWord weight
      (fun i => by dsimp [weight, lieGrowthBasisWeight]; omega) n
  letI : FiniteDimensional k
      (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration b weight n) :=
    UniversalEnvelopingAlgebra.finiteDimensional_orderedMonomialWeightFiltration
      b weight n
  calc
    (sfinrank k
        (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
          b weight n) : ℚ) =
        Fintype.card
          (UniversalEnvelopingAlgebra.BoundedWeightPBWWord weight n) := by
      exact_mod_cast
        UniversalEnvelopingAlgebra.finrank_orderedMonomialWeightFiltration
          b weight n
    _ = Nat.card
        (UniversalEnvelopingAlgebra.BoundedWeightPBWWord weight n) := by
      rw [Nat.card_eq_fintype_card]
    _ ≤ D * q ^ n := hbound n

/-- Algebra balls generated inside weighted radius `d` stay inside weighted
radius `d*n`. -/
theorem associativeGrowthBall_le_orderedMonomialWeightFiltration
    {L : Type v} [LieRing L] [LieAlgebra k L]
    {ι : Type*} [LinearOrder ι] (b : Module.Basis ι k L)
    (weight : ι → ℕ)
    (hweight : UniversalEnvelopingAlgebra.BracketWeightCompatible b weight)
    (P : Submodule k (UniversalEnvelopingAlgebra k L)) (d : ℕ)
    (hP : P ≤ UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
      b weight d) : ∀ n,
    associativeGrowthBall k P n ≤
      UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
        b weight (d * n) := by
  intro n
  induction n with
  | zero =>
      rw [associativeGrowthBall]
      rw [Submodule.span_singleton_le_iff_mem]
      let word : UniversalEnvelopingAlgebra.PBWWord ι := ⟨[], by simp⟩
      have hword :=
        UniversalEnvelopingAlgebra.orderedMonomial_mem_weightFiltration
          b weight word (n := 0)
            (by
              change UniversalEnvelopingAlgebra.pbwListWeight weight
                ([] : List ι) ≤ 0
              simp [UniversalEnvelopingAlgebra.pbwListWeight])
      simpa [UniversalEnvelopingAlgebra.orderedMonomial,
        UniversalEnvelopingAlgebra.pbwMonomial, word] using hword
  | succ n ih =>
      rw [associativeGrowthBall, sup_le_iff]
      constructor
      · exact ih.trans
          (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration_mono
            b weight (Nat.mul_le_mul_left d (Nat.le_succ n)))
      · rw [Submodule.mul_le]
        intro x hx y hy
        simpa only [Nat.mul_succ, Nat.add_comm] using
          (UniversalEnvelopingAlgebra.mul_mem_orderedMonomialWeightFiltration
            b weight hweight (hP hx) (ih hy))

set_option linter.style.haveILetI false in
/-- Smith's theorem in the form needed here: genuine subexponential Lie
growth gives subexponential growth of every finite coefficient filtration
in the universal enveloping algebra. -/
theorem hasSubexponentialAlgebraGrowth_uea_of_generatingSubspace
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) [FiniteDimensional k F]
    (hspan : LieSubalgebra.lieSpan k L (F : Set L) = ⊤)
    (hsub : IsSubexponentialSequence
      (fun n => sfinrank k (lieGrowthBall k F n)))
    [LinearOrder (LieGrowthBasisIndex k F)]
    [Nonempty (LieGrowthBasisIndex k F)] :
    HasSubexponentialAlgebraGrowth
      (k := k) (A := UniversalEnvelopingAlgebra k L) := by
  intro P hP
  let _ : FiniteDimensional k P := hP
  let b := lieGrowthBasis k F hspan
  let weight := lieGrowthBasisWeight (k := k) (F := F)
  have hweight : UniversalEnvelopingAlgebra.BracketWeightCompatible b weight :=
    lieGrowthBasis_bracketWeightCompatible k F hspan
  obtain ⟨d, hPd⟩ :=
    UniversalEnvelopingAlgebra.exists_le_orderedMonomialWeightFiltration_of_finite
      b weight P
  have hfiltration := isSubexponentialSequence_lieGrowthPBWFiltration
    k F hspan hsub
  have hscaled := hfiltration.comp_mul
    (fun n => sfinrank k
      (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
        b weight n)) d
  intro q hq
  obtain ⟨C, hC, hbound⟩ := hscaled q hq
  refine ⟨C, hC, fun n => ?_⟩
  letI : Fintype
      (UniversalEnvelopingAlgebra.WeightSublevel weight (d * n)) :=
    fintypeLieGrowthWeightSublevel k F (d * n)
  letI : Fintype
      (UniversalEnvelopingAlgebra.BoundedWeightPBWWord weight (d * n)) :=
    UniversalEnvelopingAlgebra.fintypeBoundedWeightPBWWord weight
      (fun i => by dsimp [weight, lieGrowthBasisWeight]; omega) (d * n)
  letI : FiniteDimensional k
      (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
        b weight (d * n)) :=
    UniversalEnvelopingAlgebra.finiteDimensional_orderedMonomialWeightFiltration
      b weight (d * n)
  have hle := associativeGrowthBall_le_orderedMonomialWeightFiltration
    k b weight hweight P d hPd n
  have hdim := Submodule.finrank_mono hle
  calc
    (sfinrank k (associativeGrowthBall k P n) : ℚ) ≤
        sfinrank k
          (UniversalEnvelopingAlgebra.orderedMonomialWeightFiltration
            b weight (d * n)) := by
      exact_mod_cast hdim
    _ ≤ C * q ^ n := hbound n

theorem associativeGrowthBall_eq_algebraBall
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (P : Submodule k (UniversalEnvelopingAlgebra k L)) (n : ℕ) :
    associativeGrowthBall k P n = algebraBall P n := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [associativeGrowthBall, algebraBall_succ, ih, actionExpansion,
        actionSubspace_regular_eq_mul]

/-- A subexponential positive sequence has a Følner consecutive ratio. -/
theorem exists_succ_ratio_le_of_subexponential
    (a : ℕ → ℕ) (ha0 : 0 < a 0)
    (hsub : IsSubexponentialSequence a)
    (ε : ℚ) (hε : 0 < ε) :
    ∃ n, (a (n + 1) : ℚ) ≤ (1 + ε) * a n := by
  obtain ⟨C, _hC, hbound⟩ := hsub (1 + ε / 2) (by linarith)
  exact exists_succ_le_mul_of_exponential_bound
    (fun n => (a n : ℚ)) (by exact_mod_cast ha0) ε hε C hbound

/-- Subexponential growth of all finite coefficient filtrations of the
universal enveloping algebra implies Lie amenability. -/
theorem isAmenableLieAlgebra_of_subexponentialUEAGrowth
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hU : HasSubexponentialAlgebraGrowth
      (k := k) (A := UniversalEnvelopingAlgebra k L)) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  apply isAmenableLieAlgebra_iff_regularActionFolner.mpr
  intro P hP ε hε
  let _ : FiniteDimensional k P := hP
  have hsub := hU P inferInstance
  obtain ⟨n, hn⟩ := exists_succ_ratio_le_of_subexponential
    (fun m ↦ sfinrank k (associativeGrowthBall k P m))
    (by
      change 0 < sfinrank k (k ∙ (1 : UniversalEnvelopingAlgebra k L))
      rw [sfinrank, finrank_span_singleton]
      · norm_num
      · intro hone
        have := congrArg (Coalgebra.counit (R := k)) hone
        simp at this)
    hsub ε hε
  let E := algebraBall P n
  let _ : FiniteDimensional k E := finiteDimensional_algebraBall P n
  have hE : E ≠ ⊥ := algebraBall_ne_bot P n
  refine ⟨E, hE, inferInstance, ?_⟩
  change (sfinrank k (algebraBall P (n + 1)) : ℚ) ≤
    (1 + ε) * sfinrank k (algebraBall P n)
  simpa only [associativeGrowthBall_eq_algebraBall] using hn

/-- Every finite-dimensional Lie algebra has genuine subexponential
growth. -/
theorem hasSubexponentialLieGrowth_of_finiteDimensional
    {L : Type v} [LieRing L] [LieAlgebra k L]
    [FiniteDimensional k L] :
    HasSubexponentialLieGrowth k L := by
  refine ⟨⊤, inferInstance, ?_, ?_⟩
  · apply top_unique
    intro x _hx
    exact LieSubalgebra.subset_lieSpan (Set.mem_univ x)
  · intro q hq
    let C : ℚ := Module.finrank k L + 1
    have hC : 0 < C := by dsimp [C]; positivity
    refine ⟨C, hC, ?_⟩
    intro n
    have hdim : sfinrank k (lieGrowthBall k (⊤ : Submodule k L) n) ≤
        Module.finrank k L := Submodule.finrank_le _
    have hpow : (1 : ℚ) ≤ q ^ n := one_le_pow₀ hq.le
    calc
      (sfinrank k (lieGrowthBall k (⊤ : Submodule k L) n) : ℚ) ≤
          Module.finrank k L := by exact_mod_cast hdim
      _ ≤ C := by dsimp [C]; linarith
      _ ≤ C * q ^ n := by
        simpa only [mul_one] using mul_le_mul_of_nonneg_left hpow hC.le

/-- In an Abelian Lie algebra every Lie ball is its generating subspace. -/
theorem lieGrowthBall_eq_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L) (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F n = F := by
  induction n with
  | zero => rfl
  | succ n ih =>
      rw [lieGrowthBall_succ, ih, lieExpansion]
      apply sup_eq_left.2
      rw [lieActionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x _hx y _hy
      change ⁅x, y⁆ ∈ F
      rw [hL.trivial x y]
      exact Submodule.zero_mem F

/-- A finitely generated Abelian Lie algebra has genuine subexponential
growth. -/
theorem hasSubexponentialLieGrowth_of_finitelyGenerated_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L)
    (hfg : IsFinitelyGeneratedLieAlgebra (k := k) L) :
    HasSubexponentialLieGrowth k L := by
  obtain ⟨s, hs⟩ := hfg
  let F : Submodule k L := Submodule.span k (s : Set L)
  have hF : FiniteDimensional k F := by
    dsimp [F]
    exact FiniteDimensional.span_of_finite k s.finite_toSet
  refine ⟨F, hF, ?_, ?_⟩
  · apply top_unique
    rw [← hs]
    exact LieSubalgebra.lieSpan_mono Submodule.subset_span
  · intro q hq
    let C : ℚ := Module.finrank k F + 1
    have hC : 0 < C := by dsimp [C]; positivity
    refine ⟨C, hC, ?_⟩
    intro n
    dsimp only
    rw [lieGrowthBall_eq_of_isLieAbelian k hL F n]
    have hpow : (1 : ℚ) ≤ q ^ n := one_le_pow₀ hq.le
    calc
      (sfinrank k F : ℚ) ≤ C := by dsimp [C, sfinrank]; norm_num
      _ ≤ C * q ^ n := by
        simpa only [mul_one] using mul_le_mul_of_nonneg_left hpow hC.le

/-- A Lie subalgebra generated by finitely many elements of an Abelian Lie
algebra is finite-dimensional. -/
theorem finiteDimensional_lieSpan_finset_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLieAbelian L) (s : Finset L) :
    FiniteDimensional k (LieSubalgebra.lieSpan k L (s : Set L)) := by
  have hzero : ∀ᵉ (x ∈ (s : Set L)) (y ∈ (s : Set L)), ⁅x, y⁆ = 0 :=
    fun x _ y _ => hL.trivial x y
  have heq := LieSubalgebra.coe_lieSpan_eq_span_of_forall_lie_eq_zero
    (R := k) (L := L) (s := (s : Set L)) hzero
  let e : LieSubalgebra.lieSpan k L (s : Set L) ≃ₗ[k]
      Submodule.span k (s : Set L) := LinearEquiv.ofEq _ _ heq
  exact FiniteDimensional.of_injective e.toLinearMap e.injective

/-! ## Amenability of locally finite-dimensional Lie algebras -/

/-- A finite-dimensional Lie algebra is amenable.  Finite PBW filtration
steps provide the Følner subspaces. -/
theorem isAmenableLieAlgebra_of_finiteDimensional
    {L : Type v} [LieRing L] [LieAlgebra k L]
    [FiniteDimensional k L] :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  apply isAmenableLieAlgebra_iff_regularActionFolner.mpr
  intro P hP ε hε
  let : FiniteDimensional k P := hP
  let b := Module.finBasis k L
  let r := Module.finrank k L
  obtain ⟨d, hPd⟩ :=
    UniversalEnvelopingAlgebra.exists_le_monomialFiltration_of_finite b P
  obtain ⟨n, hn⟩ :=
    UniversalEnvelopingAlgebra.exists_choose_shift_le r d ε hε
  let E := UniversalEnvelopingAlgebra.monomialFiltration b n
  let : FiniteDimensional k E :=
    UniversalEnvelopingAlgebra.finiteDimensional_monomialFiltration b n
  have hE : E ≠ ⊥ := by
    intro hbot
    have hone : (1 : UniversalEnvelopingAlgebra k L) ∈ E := by
      rw [← UniversalEnvelopingAlgebra.pbwMonomial_nil b]
      exact UniversalEnvelopingAlgebra.pbwMonomial_mem_filtration b [] (by simp)
    rw [hbot, Submodule.mem_bot] at hone
    have hne : (1 : UniversalEnvelopingAlgebra k L) ≠ 0 := by
      intro h
      have := congrArg (Coalgebra.counit (R := k)) h
      simp at this
    exact hne hone
  have hexp : actionExpansion P E ≤
      UniversalEnvelopingAlgebra.monomialFiltration b (d + n) := by
    rw [actionExpansion, sup_le_iff]
    constructor
    · exact UniversalEnvelopingAlgebra.monomialFiltration_mono b
        (Nat.le_add_left n d)
    · rw [actionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x hx y hy
      exact UniversalEnvelopingAlgebra.mul_mem_monomialFiltration b
        (hPd hx) hy
  refine ⟨E, hE, inferInstance, ?_⟩
  let : FiniteDimensional k
      (UniversalEnvelopingAlgebra.monomialFiltration b (d + n)) :=
    UniversalEnvelopingAlgebra.finiteDimensional_monomialFiltration b (d + n)
  have hdim := Submodule.finrank_mono hexp
  rw [sfinrank, sfinrank]
  calc
    (Module.finrank k (actionExpansion P E) : ℚ) ≤
        (Module.finrank k
          (UniversalEnvelopingAlgebra.monomialFiltration b (d + n)) : ℚ) :=
      by exact_mod_cast hdim
    _ = (((d + n + r).choose r : ℕ) : ℚ) := by
      rw [UniversalEnvelopingAlgebra.finrank_monomialFiltration]
      simp only [Fintype.card_fin, r]
    _ ≤ (1 + ε) * (((n + r).choose r : ℕ) : ℚ) := by
      simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using hn
    _ = (1 + ε) * Module.finrank k E := by
      rw [show Module.finrank k E = (n + r).choose r by
        change Module.finrank k
          (UniversalEnvelopingAlgebra.monomialFiltration b n) = _
        rw [UniversalEnvelopingAlgebra.finrank_monomialFiltration]
        simp only [Fintype.card_fin, r]]

/-- Every finitely generated Lie algebra of genuine subexponential growth
is amenable; this is the PBW/Smith clause of Theorem G. -/
theorem isAmenableLieAlgebra_of_hasSubexponentialLieGrowth
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : HasSubexponentialLieGrowth k L) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  classical
  obtain ⟨F, hF, hspan, hsub⟩ := hL
  let _ : FiniteDimensional k F := hF
  let β := LieGrowthBasisIndex k F
  let b := lieGrowthBasis k F hspan
  let _ : LinearOrder β := WellOrderingRel.isWellOrder.linearOrder
  cases isEmpty_or_nonempty β with
  | inl hempty =>
      let _ : IsEmpty β := hempty
      let _ : Fintype β := Fintype.ofFinite β
      let _ : Module.Finite k L := Module.Finite.of_basis b
      exact isAmenableLieAlgebra_of_finiteDimensional (k := k)
  | inr hnonempty =>
      let _ : Nonempty β := hnonempty
      apply isAmenableLieAlgebra_of_subexponentialUEAGrowth
      exact hasSubexponentialAlgebraGrowth_uea_of_generatingSubspace
        k F hspan hsub

/-- The Lie subalgebra generated by a finite set is finitely generated as
an abstract Lie algebra. -/
theorem isFinitelyGeneratedLieAlgebra_lieSpan_finset
    {L : Type v} [LieRing L] [LieAlgebra k L] (s : Finset L) :
    IsFinitelyGeneratedLieAlgebra (k := k)
      (LieSubalgebra.lieSpan k L (s : Set L)) := by
  classical
  let S := LieSubalgebra.lieSpan k L (s : Set L)
  let f : {x // x ∈ s} → S := fun x =>
    ⟨x.1, LieSubalgebra.subset_lieSpan x.2⟩
  let t : Finset S := Finset.univ.image f
  refine ⟨t, ?_⟩
  have ht : (t : Set S) = Set.range f := by
    ext x
    simp [t]
  rw [ht, ← LieSubalgebra.comap_lieSpan_range_eq k S f]
  have hrange : Set.range ((↑) ∘ f) = (s : Set L) := by
    ext x
    constructor
    · rintro ⟨i, rfl⟩
      exact i.2
    · intro hx
      exact ⟨⟨x, hx⟩, rfl⟩
  rw [hrange]
  change LieSubalgebra.comap S.incl S = ⊤
  exact (LieSubalgebra.comap_incl_eq_top k S S).mpr le_rfl

/-- Every Abelian Lie algebra is locally of subexponential growth. -/
theorem hasLocallySubexponentialGrowth_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L] (hL : IsLieAbelian L) :
    HasLocallySubexponentialGrowth k L := by
  intro S hSfg
  apply hasSubexponentialLieGrowth_of_finitelyGenerated_of_isLieAbelian
  · exact ⟨fun x y => Subtype.ext (hL.trivial x.1 y.1)⟩
  · exact hSfg

/-- The locally subexponential-growth clause of Theorem G. -/
theorem isAmenableLieAlgebra_of_locallySubexponentialGrowth
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : HasLocallySubexponentialGrowth k L) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  classical
  let S : Finset L → LieSubalgebra k L := fun s =>
    LieSubalgebra.lieSpan k L (s : Set L)
  apply isAmenableLieAlgebra_directedUnion S
  · intro s t
    refine ⟨s ∪ t, ?_, ?_⟩
    · exact LieSubalgebra.lieSpan_mono Finset.subset_union_left
    · exact LieSubalgebra.lieSpan_mono Finset.subset_union_right
  · apply top_unique
    intro x _hx
    exact (le_iSup S {x})
      (LieSubalgebra.subset_lieSpan (by simp))
  · intro s
    apply isAmenableLieAlgebra_of_hasSubexponentialLieGrowth
    exact hL (S s) (by
      dsimp [S]
      exact isFinitelyGeneratedLieAlgebra_lieSpan_finset k s)

/-- In particular, every Abelian Lie algebra is amenable. -/
theorem isAmenableLieAlgebra_of_isLieAbelian
    {L : Type v} [LieRing L] [LieAlgebra k L] (hL : IsLieAbelian L) :
    IsAmenableLieAlgebra (k := k) (L := L) :=
  isAmenableLieAlgebra_of_locallySubexponentialGrowth k
    (hasLocallySubexponentialGrowth_of_isLieAbelian k hL)

/-- A locally finite-dimensional Lie algebra is a directed union of its
finite-dimensional Lie subalgebras, hence is amenable. -/
theorem IsLocallyFiniteDimensionalLieAlgebra.isAmenableLieAlgebra
    {L : Type v} [LieRing L] [LieAlgebra k L]
    (hL : IsLocallyFiniteDimensionalLieAlgebra k L) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  let ι := {S : LieSubalgebra k L // Module.Finite k S}
  let S : ι → LieSubalgebra k L := fun i => i.1
  let _ : Nonempty ι := ⟨⟨⊥, Module.Finite.bot k L⟩⟩
  have hdir : Directed (· ≤ ·) S := by
    intro A B
    let : Module.Finite k A.1 := A.2
    let : Module.Finite k B.1 := B.2
    let P : Submodule k L := A.1.toSubmodule ⊔ B.1.toSubmodule
    let : FiniteDimensional k P :=
      Submodule.finite_sup A.1.toSubmodule B.1.toSubmodule
    obtain ⟨T, hPT, hT⟩ := hL P inferInstance
    exact ⟨⟨T, hT⟩,
      fun x hx => hPT ((le_sup_left : A.1.toSubmodule ≤ P) hx),
      fun x hx => hPT ((le_sup_right : B.1.toSubmodule ≤ P) hx)⟩
  have hsup : iSup S = ⊤ := by
    apply top_unique
    intro x _hx
    let P : Submodule k L := k ∙ x
    let : FiniteDimensional k P := by dsimp [P]; infer_instance
    obtain ⟨T, hPT, hT⟩ := hL P inferInstance
    exact le_iSup S ⟨T, hT⟩
      (hPT (Submodule.mem_span_singleton_self x))
  apply isAmenableLieAlgebra_directedUnion S hdir hsup
  intro i
  let : FiniteDimensional k i.1 := i.2
  exact isAmenableLieAlgebra_of_finiteDimensional (k := k)

end

end HopfAmenability
