/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.TheoremD

/-!
# Growth conditions for Lie algebras

This file contains the reusable definitions of Lie balls, local finite
dimensionality, and exponential Lie growth used by Theorem F.
-/

namespace HopfAmenability

noncomputable section

universe u v

variable (k : Type u) [Field k]

/-- Lie balls generated by a coefficient subspace. -/
def lieGrowthBall {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : ℕ → Submodule k L
  | 0 => F
  | n + 1 => lieExpansion F (lieGrowthBall F n)

@[simp]
theorem lieGrowthBall_zero {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : lieGrowthBall k F 0 = F := rfl

@[simp]
theorem lieGrowthBall_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F (n + 1) = lieExpansion F (lieGrowthBall k F n) := rfl

/-- A Lie algebra is locally finite-dimensional if every finite-dimensional
subspace is contained in a finite-dimensional Lie subalgebra. -/
def IsLocallyFiniteDimensionalLieAlgebra
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ P : Submodule k L, FiniteDimensional k P →
    ∃ S : LieSubalgebra k L,
      P ≤ S.toSubmodule ∧ FiniteDimensional k S

/-- Exponential Lie growth with respect to a finite-dimensional generating
subspace. -/
def HasExponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    Module.Finite k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      ∃ q : ℚ, 1 < q ∧ ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
        q ^ n ≤ (sfinrank k (lieGrowthBall k F n) : ℚ)

/-! ## Amenability of locally finite-dimensional Lie algebras -/

/-- A finite-dimensional Lie algebra is amenable.  Finite PBW filtration
steps provide the Følner subspaces. -/
theorem isAmenableLieAlgebra_of_finiteDimensional
    {L : Type v} [LieRing L] [LieAlgebra k L] [CharZero k]
    [FiniteDimensional k L] :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  intro P hP ε hε
  let : FiniteDimensional k P := hP
  let b := Module.finBasis k L
  let r := Module.finrank k L
  obtain ⟨d, hPd⟩ :=
    UniversalEnvelopingAlgebra.exists_le_monomialFiltration_of_finite b P
  obtain ⟨n, hn⟩ :=
    UniversalEnvelopingAlgebra.exists_choose_shift_le r d ε hε
  let E := UniversalEnvelopingAlgebra.monomialFiltration b n
  let : FiniteDimensional k E :=
    UniversalEnvelopingAlgebra.finiteDimensional_monomialFiltration b n
  have hE : E ≠ ⊥ := by
    intro hbot
    have hone : (1 : UniversalEnvelopingAlgebra k L) ∈ E := by
      rw [← UniversalEnvelopingAlgebra.pbwMonomial_nil b]
      exact UniversalEnvelopingAlgebra.pbwMonomial_mem_filtration b [] (by simp)
    rw [hbot, Submodule.mem_bot] at hone
    have hne : (1 : UniversalEnvelopingAlgebra k L) ≠ 0 := by
      intro h
      have := congrArg (Coalgebra.counit (R := k)) h
      simp at this
    exact hne hone
  have hexp : actionExpansion P E ≤
      UniversalEnvelopingAlgebra.monomialFiltration b (d + n) := by
    rw [actionExpansion, sup_le_iff]
    constructor
    · exact UniversalEnvelopingAlgebra.monomialFiltration_mono b
        (Nat.le_add_left n d)
    · rw [actionSubspace_eq_map₂]
      apply Submodule.map₂_le.2
      intro x hx y hy
      exact UniversalEnvelopingAlgebra.mul_mem_monomialFiltration b
        (hPd hx) hy
  refine ⟨E, hE, inferInstance, ?_⟩
  let : FiniteDimensional k
      (UniversalEnvelopingAlgebra.monomialFiltration b (d + n)) :=
    UniversalEnvelopingAlgebra.finiteDimensional_monomialFiltration b (d + n)
  have hdim := Submodule.finrank_mono hexp
  rw [sfinrank, sfinrank]
  calc
    (Module.finrank k (actionExpansion P E) : ℚ) ≤
        (Module.finrank k
          (UniversalEnvelopingAlgebra.monomialFiltration b (d + n)) : ℚ) :=
      by exact_mod_cast hdim
    _ = (((d + n + r).choose r : ℕ) : ℚ) := by
      rw [UniversalEnvelopingAlgebra.finrank_monomialFiltration]
      simp only [Fintype.card_fin, r]
    _ ≤ (1 + ε) * (((n + r).choose r : ℕ) : ℚ) := by
      simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using hn
    _ = (1 + ε) * Module.finrank k E := by
      rw [show Module.finrank k E = (n + r).choose r by
        change Module.finrank k
          (UniversalEnvelopingAlgebra.monomialFiltration b n) = _
        rw [UniversalEnvelopingAlgebra.finrank_monomialFiltration]
        simp only [Fintype.card_fin, r]]

/-- A locally finite-dimensional Lie algebra is a directed union of its
finite-dimensional Lie subalgebras, hence is amenable. -/
theorem IsLocallyFiniteDimensionalLieAlgebra.isAmenableLieAlgebra
    {L : Type v} [LieRing L] [LieAlgebra k L] [CharZero k]
    (hL : IsLocallyFiniteDimensionalLieAlgebra k L) :
    IsAmenableLieAlgebra (k := k) (L := L) := by
  let ι := {S : LieSubalgebra k L // Module.Finite k S}
  let S : ι → LieSubalgebra k L := fun i => i.1
  let _ : Nonempty ι := ⟨⟨⊥, Module.Finite.bot k L⟩⟩
  have hdir : Directed (· ≤ ·) S := by
    intro A B
    let : Module.Finite k A.1 := A.2
    let : Module.Finite k B.1 := B.2
    let P : Submodule k L := A.1.toSubmodule ⊔ B.1.toSubmodule
    let : FiniteDimensional k P :=
      Submodule.finite_sup A.1.toSubmodule B.1.toSubmodule
    obtain ⟨T, hPT, hT⟩ := hL P inferInstance
    exact ⟨⟨T, hT⟩,
      fun x hx => hPT ((le_sup_left : A.1.toSubmodule ≤ P) hx),
      fun x hx => hPT ((le_sup_right : B.1.toSubmodule ≤ P) hx)⟩
  have hsup : iSup S = ⊤ := by
    apply top_unique
    intro x _hx
    let P : Submodule k L := k ∙ x
    let : FiniteDimensional k P := by dsimp [P]; infer_instance
    obtain ⟨T, hPT, hT⟩ := hL P inferInstance
    exact le_iSup S ⟨T, hT⟩
      (hPT (Submodule.mem_span_singleton_self x))
  apply isAmenableLieAlgebra_directedUnion S hdir hsup
  intro i
  let : FiniteDimensional k i.1 := i.2
  exact isAmenableLieAlgebra_of_finiteDimensional (k := k)

end

end HopfAmenability
