/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.TheoremD

/-!
# Theorem F: an amenable Lie algebra of exponential growth

This file formalizes the exponential-growth example from the accompanying
article.  The example is a finitely generated Lie algebra which is an
extension of a locally finite-dimensional ideal by a one-dimensional Lie
algebra.
-/

namespace HopfAmenability

noncomputable section

universe u v

variable (k : Type u) [Field k]

/-- Lie balls generated by a coefficient subspace. -/
def lieGrowthBall {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) : ℕ → Submodule k L
  | 0 => F
  | n + 1 => lieExpansion F (lieGrowthBall F n)

@[simp]
theorem lieGrowthBall_zero {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) :
    lieGrowthBall k F 0 = F :=
  rfl

@[simp]
theorem lieGrowthBall_succ {L : Type v} [LieRing L] [LieAlgebra k L]
    (F : Submodule k L) (n : ℕ) :
    lieGrowthBall k F (n + 1) = lieExpansion F (lieGrowthBall k F n) :=
  rfl

/-- A Lie algebra is locally finite-dimensional if every finite-dimensional
subspace is contained in a finite-dimensional Lie subalgebra. -/
def IsLocallyFiniteDimensionalLieAlgebra
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∀ P : Submodule k L, FiniteDimensional k P →
    ∃ S : LieSubalgebra k L,
      P ≤ S.toSubmodule ∧ FiniteDimensional k S

/-- Exponential Lie growth with respect to a finite-dimensional generating
subspace. -/
def HasExponentialLieGrowth
    (L : Type v) [LieRing L] [LieAlgebra k L] : Prop :=
  ∃ F : Submodule k L,
    FiniteDimensional k F ∧
      LieSubalgebra.lieSpan k L (F : Set L) = ⊤ ∧
      ∃ q : ℚ, 1 < q ∧ ∃ N : ℕ, ∀ n : ℕ, N ≤ n →
        q ^ n ≤ (sfinrank k (lieGrowthBall k F n) : ℚ)

/-- The collection of properties asserted of the example in Theorem F.
The quotient by `K` is the displayed one-dimensional quotient in the exact
sequence of the article. -/
structure ExponentialLocallyFiniteByOneExample where
  L : LieAlgebraObject.{u, v} k
  K : LieIdeal k L.Carrier
  finitelyGenerated : IsFinitelyGeneratedLieAlgebra (k := k) L.Carrier
  exponentialGrowth : HasExponentialLieGrowth k L.Carrier
  locallyFiniteKernel : IsLocallyFiniteDimensionalLieAlgebra k K
  quotientFiniteDimensional : FiniteDimensional k (L.Carrier ⧸ K)
  quotientFinrank : Module.finrank k (L.Carrier ⧸ K) = 1
  amenable : IsAmenableLieAlgebra (k := k) (L := L.Carrier)

end

end HopfAmenability
