/-
Copyright (c) 2026 Laurent Bartholdi. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Laurent Bartholdi, based on code by ChatGPT 5.6 Sol
-/

import Amenability.UniversalEnvelopingCoalgebra
import Amenability.SubmoduleFinrank
import Mathlib.LinearAlgebra.TensorProduct.Finiteness
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas
import Mathlib.LinearAlgebra.Dimension.Constructions
import Mathlib.RingTheory.TensorProduct.Finite

/-! # Finite-word generation in universal enveloping algebras -/

open Coalgebra Module
namespace HopfAmenability
noncomputable section
universe u v
variable {k : Type u} {L : Type v}
variable [Field k] [LieRing L] [LieAlgebra k L]
local notation "U" => UniversalEnvelopingAlgebra k L
attribute [local instance 100] LieRing.ofAssociativeRing

/-- The unital finite-dimensional coefficient space generated by a Lie test
space. -/
def ueaGeneratorSubspace (F : Submodule k L) : Submodule k U :=
  k ∙ (1 : U) ⊔
    Submodule.map (UniversalEnvelopingAlgebra.ι k).toLinearMap F

theorem finiteDimensional_ueaGeneratorSubspace
    (F : Submodule k L) [FiniteDimensional k F] :
    FiniteDimensional k (ueaGeneratorSubspace (k := k) F) := by
  rw [ueaGeneratorSubspace]
  infer_instance

theorem one_mem_ueaGeneratorSubspace (F : Submodule k L) :
    (1 : U) ∈ ueaGeneratorSubspace (k := k) F :=
  Submodule.mem_sup_left (Submodule.mem_span_singleton_self 1)

theorem ueaGeneratorSubspace_mono {F G : Submodule k L} (hFG : F ≤ G) :
    ueaGeneratorSubspace (k := k) F ≤ ueaGeneratorSubspace (k := k) G :=
  sup_le_sup_left (Submodule.map_mono hFG) _

theorem ueaGeneratorSubspace_pow_le_succ (F : Submodule k L) (n : ℕ) :
    ueaGeneratorSubspace (k := k) F ^ n ≤
      ueaGeneratorSubspace (k := k) F ^ (n + 1) := by
  rw [Submodule.pow_succ]
  intro x hx
  simpa using Submodule.mul_mem_mul hx (one_mem_ueaGeneratorSubspace F)

theorem ueaGeneratorSubspace_pow_mono_nat (F : Submodule k L)
    {m n : ℕ} (hmn : m ≤ n) :
    ueaGeneratorSubspace (k := k) F ^ m ≤
      ueaGeneratorSubspace (k := k) F ^ n := by
  induction n, hmn using Nat.le_induction with
  | base => exact le_rfl
  | succ n hmn ih =>
      exact ih.trans (ueaGeneratorSubspace_pow_le_succ F n)

theorem ueaGeneratorSubspace_pow_mono {F G : Submodule k L}
    (hFG : F ≤ G) (n : ℕ) :
    ueaGeneratorSubspace (k := k) F ^ n ≤
      ueaGeneratorSubspace (k := k) G ^ n := by
  induction n with
  | zero => exact le_rfl
  | succ n ih =>
      rw [Submodule.pow_succ, Submodule.pow_succ]
      apply Submodule.mul_le.2
      intro x hx y hy
      exact Submodule.mul_mem_mul (ih hx)
        (ueaGeneratorSubspace_mono hFG hy)

/-- Elements expressible using a finite-dimensional Lie coefficient space
and a positive bounded word length form a subalgebra of `U(L)`. -/
def ueaFiniteWordSubalgebra : Subalgebra k U where
  carrier := {x | ∃ (F : Submodule k L), FiniteDimensional k F ∧
    ∃ n : ℕ, 0 < n ∧ x ∈ ueaGeneratorSubspace (k := k) F ^ n}
  add_mem' := by
    rintro x y ⟨F, hF, m, hm, hxm⟩ ⟨G, hG, n, hn, hyn⟩
    refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, max m n,
      lt_of_lt_of_le hm (le_max_left _ _), ?_⟩
    apply Submodule.add_mem
    · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_left _ _)
        (ueaGeneratorSubspace_pow_mono le_sup_left m hxm)
    · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_right _ _)
        (ueaGeneratorSubspace_pow_mono le_sup_right n hyn)
  mul_mem' := by
    rintro x y ⟨F, hF, m, hm, hxm⟩ ⟨G, hG, n, hn, hyn⟩
    refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, m + n,
      Nat.add_pos_left hm n, ?_⟩
    rw [Submodule.pow_add (ueaGeneratorSubspace (k := k) (F ⊔ G))
      (Nat.ne_of_gt hn)]
    exact Submodule.mul_mem_mul
      (ueaGeneratorSubspace_pow_mono le_sup_left m hxm)
      (ueaGeneratorSubspace_pow_mono le_sup_right n hyn)
  algebraMap_mem' := by
    intro r
    refine ⟨⊥, inferInstance, 1, Nat.zero_lt_succ 0, ?_⟩
    rw [pow_one]
    have hone := one_mem_ueaGeneratorSubspace (k := k) (⊥ : Submodule k L)
    simpa only [Algebra.smul_def, mul_one] using
      (ueaGeneratorSubspace (k := k) (⊥ : Submodule k L)).smul_mem r hone

theorem ueaFiniteWordSubalgebra_eq_top :
    ueaFiniteWordSubalgebra (k := k) (L := L) = ⊤ := by
  let A := ueaFiniteWordSubalgebra (k := k) (L := L)
  have hi : ∀ x : L, UniversalEnvelopingAlgebra.ι k x ∈ A := by
    intro x
    let F : Submodule k L := k ∙ x
    refine ⟨F, by infer_instance, 1, Nat.zero_lt_succ 0, ?_⟩
    rw [pow_one]
    exact Submodule.mem_sup_right ⟨x,
      Submodule.mem_span_singleton_self x, rfl⟩
  let iA : LieHom k L A :=
    { toLinearMap := (UniversalEnvelopingAlgebra.ι k).toLinearMap.codRestrict
        A.toSubmodule hi
      map_lie' := fun {x y} => by
        apply Subtype.ext
        exact LieHom.map_lie (UniversalEnvelopingAlgebra.ι k) x y }
  let liftA : U →ₐ[k] A := UniversalEnvelopingAlgebra.lift k iA
  have hval : A.val.comp liftA = AlgHom.id k U := by
    apply UniversalEnvelopingAlgebra.hom_ext
    apply DFunLike.ext _ _
    intro x
    change A.val (liftA (UniversalEnvelopingAlgebra.ι k x)) =
      UniversalEnvelopingAlgebra.ι k x
    rw [show liftA (UniversalEnvelopingAlgebra.ι k x) = iA x from
      UniversalEnvelopingAlgebra.lift_ι_apply k iA x]
    rfl
  apply top_unique
  intro x _
  have hx : A.val (liftA x) = x := DFunLike.congr_fun hval x
  rw [← hx]
  exact (liftA x).property

/-- Every element of `U(L)` is contained in a bounded power of a generator
space coming from finitely many Lie elements. -/
theorem exists_mem_ueaGeneratorSubspace_pow (x : U) :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ x ∈ ueaGeneratorSubspace (k := k) F ^ n := by
  have hx : x ∈ ueaFiniteWordSubalgebra (k := k) (L := L) := by
    rw [ueaFiniteWordSubalgebra_eq_top]
    trivial
  exact hx

theorem exists_generator_pow_containing_basis_finset
    {ι : Type*} (b : Basis ι k U) (t : Finset ι) :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ ∀ i ∈ t,
        b i ∈ ueaGeneratorSubspace (k := k) F ^ n := by
  classical
  induction t using Finset.induction_on with
  | empty =>
      refine ⟨⊥, inferInstance, 1, Nat.zero_lt_succ 0, ?_⟩
      simp
  | @insert i t hi ih =>
      obtain ⟨F, hF, m, hm, him⟩ := exists_mem_ueaGeneratorSubspace_pow (b i)
      obtain ⟨G, hG, n, hn, htn⟩ := ih
      refine ⟨F ⊔ G, Submodule.finiteDimensional_sup F G, max m n,
        lt_of_lt_of_le hm (le_max_left _ _), ?_⟩
      intro j hj
      rw [Finset.mem_insert] at hj
      rcases hj with rfl | hj
      · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_left _ _)
          (ueaGeneratorSubspace_pow_mono le_sup_left m him)
      · exact ueaGeneratorSubspace_pow_mono_nat (F ⊔ G) (le_max_right _ _)
          (ueaGeneratorSubspace_pow_mono le_sup_right n (htn j hj))

theorem Basis.exists_finset_support_field
    {ι : Type*} (b : Basis ι k U) (P : Submodule k U)
    [FiniteDimensional k P] :
    ∃ t : Finset ι, ∀ x ∈ P, (b.repr x).support ⊆ t := by
  classical
  let e := Module.finBasis k P
  let t : Finset ι := Finset.univ.biUnion fun i =>
    (b.repr (e i : U)).support
  refine ⟨t, ?_⟩
  intro x hx
  let xP : P := ⟨x, hx⟩
  have hxsum : ∑ i, (e.repr xP i) • (e i : U) = x := by
    have h := congrArg P.subtype (e.sum_repr xP)
    rw [map_sum] at h
    simpa using h
  rw [← hxsum, map_sum]
  refine Finsupp.support_finsetSum.trans ?_
  apply Finset.biUnion_subset.2
  intro i hi
  rw [map_smul]
  exact Finsupp.support_smul.trans
    (Finset.subset_biUnion_of_mem
      (fun j => (b.repr (e j : U)).support) (Finset.mem_univ i))

/-- A finite-dimensional subspace of `U(L)` is contained in a bounded power
of a generator space coming from a finite-dimensional subspace of `L`. -/
theorem exists_ueaGeneratorSubspace_pow_containing
    (P : Submodule k U) [FiniteDimensional k P] :
    ∃ (F : Submodule k L), FiniteDimensional k F ∧
      ∃ n : ℕ, 0 < n ∧ P ≤ ueaGeneratorSubspace (k := k) F ^ n := by
  classical
  let ι := Module.Basis.ofVectorSpaceIndex k U
  let b : Basis ι k U := Module.Basis.ofVectorSpace k U
  obtain ⟨t, ht⟩ := Basis.exists_finset_support_field (k := k) b P
  obtain ⟨F, hF, n, hn, htn⟩ :=
    exists_generator_pow_containing_basis_finset b t
  refine ⟨F, hF, n, hn, ?_⟩
  intro x hx
  have hsum := b.linearCombination_repr x
  rw [Finsupp.linearCombination_apply] at hsum
  rw [← hsum]
  apply Submodule.sum_mem
  intro i hi
  exact Submodule.smul_mem _ _ (htn i (ht x hx hi))

/-- Multiplying finite-dimensional subspaces cannot have dimension larger
than the product of their dimensions. -/
theorem finrank_submodule_mul_le (P Q : Submodule k U)
    [FiniteDimensional k P] [FiniteDimensional k Q] :
    sfinrank k (P * Q) ≤ sfinrank k P * sfinrank k Q := by
  rw [sfinrank, sfinrank, sfinrank, Submodule.mul_eq_map₂,
    TensorProduct.map₂_eq_range_lift_comp_mapIncl]
  calc
    Module.finrank k ↑(LinearMap.range
        (TensorProduct.lift (LinearMap.mul k U) ∘ₗ
          TensorProduct.mapIncl P Q)) ≤
        Module.finrank k (TensorProduct k P Q) :=
      LinearMap.finrank_range_le
        (TensorProduct.lift (LinearMap.mul k U) ∘ₗ TensorProduct.mapIncl P Q)
    _ = Module.finrank k P * Module.finrank k Q :=
      Module.finrank_tensorProduct

theorem finiteDimensional_submodule_pow (P : Submodule k U)
    [FiniteDimensional k P] (n : ℕ) : FiniteDimensional k ↑(P ^ n) := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero, Submodule.one_eq_span]
      infer_instance
  | succ n hn =>
      rw [Submodule.pow_succ, Submodule.mul_eq_map₂,
        TensorProduct.map₂_eq_range_lift_comp_mapIncl]
      exact Module.Finite.range _

/-- The powers of a finite-dimensional coefficient space have the expected
elementary dimension bound. -/
theorem finrank_submodule_pow_le (P : Submodule k U)
    [FiniteDimensional k P] (n : ℕ) :
    sfinrank k (P ^ n) ≤ sfinrank k P ^ n := by
  induction n with
  | zero =>
      rw [Submodule.pow_zero]
      rw [sfinrank, Submodule.one_eq_span]
      have hone : (1 : U) ≠ 0 := by
        intro h
        have := congrArg (Coalgebra.counit (R := k)) h
        simp at this
      rw [finrank_span_singleton hone]
      norm_num
  | succ n ih =>
      let _ : FiniteDimensional k ↑(P ^ n) :=
        finiteDimensional_submodule_pow P n
      rw [Submodule.pow_succ, pow_succ]
      exact (finrank_submodule_mul_le (P ^ n) P).trans
        (Nat.mul_le_mul_right _ ih)

end
end HopfAmenability
